// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/locking_service.proto
// Protobuf Java Version: 4.33.4

package sdv.services.locking;

/**
 * Protobuf type {@code sdv.services.locking.GetLockStateResponse}
 */
@com.google.protobuf.Generated
public final class GetLockStateResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sdv.services.locking.GetLockStateResponse)
    GetLockStateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "GetLockStateResponse");
  }
  // Use GetLockStateResponse.newBuilder() to construct.
  private GetLockStateResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetLockStateResponse() {
    door_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sdv.services.locking.LockingServiceOuterClass.internal_static_sdv_services_locking_GetLockStateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sdv.services.locking.LockingServiceOuterClass.internal_static_sdv_services_locking_GetLockStateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sdv.services.locking.GetLockStateResponse.class, sdv.services.locking.GetLockStateResponse.Builder.class);
  }

  public static final int DOOR_FIELD_NUMBER = 1;
  private int door_ = 0;
  /**
   * <code>.sdv.services.locking.Door door = 1;</code>
   * @return The enum numeric value on the wire for door.
   */
  @java.lang.Override public int getDoorValue() {
    return door_;
  }
  /**
   * <code>.sdv.services.locking.Door door = 1;</code>
   * @return The door.
   */
  @java.lang.Override public sdv.services.locking.Door getDoor() {
    sdv.services.locking.Door result = sdv.services.locking.Door.forNumber(door_);
    return result == null ? sdv.services.locking.Door.UNRECOGNIZED : result;
  }

  public static final int IS_LOCKED_FIELD_NUMBER = 2;
  private boolean isLocked_ = false;
  /**
   * <code>bool is_locked = 2;</code>
   * @return The isLocked.
   */
  @java.lang.Override
  public boolean getIsLocked() {
    return isLocked_;
  }

  public static final int IS_OPEN_FIELD_NUMBER = 3;
  private boolean isOpen_ = false;
  /**
   * <code>bool is_open = 3;</code>
   * @return The isOpen.
   */
  @java.lang.Override
  public boolean getIsOpen() {
    return isOpen_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (door_ != sdv.services.locking.Door.DOOR_UNKNOWN.getNumber()) {
      output.writeEnum(1, door_);
    }
    if (isLocked_ != false) {
      output.writeBool(2, isLocked_);
    }
    if (isOpen_ != false) {
      output.writeBool(3, isOpen_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (door_ != sdv.services.locking.Door.DOOR_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, door_);
    }
    if (isLocked_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isLocked_);
    }
    if (isOpen_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isOpen_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sdv.services.locking.GetLockStateResponse)) {
      return super.equals(obj);
    }
    sdv.services.locking.GetLockStateResponse other = (sdv.services.locking.GetLockStateResponse) obj;

    if (door_ != other.door_) return false;
    if (getIsLocked()
        != other.getIsLocked()) return false;
    if (getIsOpen()
        != other.getIsOpen()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOOR_FIELD_NUMBER;
    hash = (53 * hash) + door_;
    hash = (37 * hash) + IS_LOCKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsLocked());
    hash = (37 * hash) + IS_OPEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOpen());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sdv.services.locking.GetLockStateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.locking.GetLockStateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.locking.GetLockStateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.locking.GetLockStateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.locking.GetLockStateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.locking.GetLockStateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.locking.GetLockStateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sdv.services.locking.GetLockStateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sdv.services.locking.GetLockStateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sdv.services.locking.GetLockStateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdv.services.locking.GetLockStateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sdv.services.locking.GetLockStateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sdv.services.locking.GetLockStateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sdv.services.locking.GetLockStateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sdv.services.locking.GetLockStateResponse)
      sdv.services.locking.GetLockStateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sdv.services.locking.LockingServiceOuterClass.internal_static_sdv_services_locking_GetLockStateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sdv.services.locking.LockingServiceOuterClass.internal_static_sdv_services_locking_GetLockStateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sdv.services.locking.GetLockStateResponse.class, sdv.services.locking.GetLockStateResponse.Builder.class);
    }

    // Construct using sdv.services.locking.GetLockStateResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      door_ = 0;
      isLocked_ = false;
      isOpen_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sdv.services.locking.LockingServiceOuterClass.internal_static_sdv_services_locking_GetLockStateResponse_descriptor;
    }

    @java.lang.Override
    public sdv.services.locking.GetLockStateResponse getDefaultInstanceForType() {
      return sdv.services.locking.GetLockStateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public sdv.services.locking.GetLockStateResponse build() {
      sdv.services.locking.GetLockStateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sdv.services.locking.GetLockStateResponse buildPartial() {
      sdv.services.locking.GetLockStateResponse result = new sdv.services.locking.GetLockStateResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(sdv.services.locking.GetLockStateResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.door_ = door_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isLocked_ = isLocked_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.isOpen_ = isOpen_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sdv.services.locking.GetLockStateResponse) {
        return mergeFrom((sdv.services.locking.GetLockStateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sdv.services.locking.GetLockStateResponse other) {
      if (other == sdv.services.locking.GetLockStateResponse.getDefaultInstance()) return this;
      if (other.door_ != 0) {
        setDoorValue(other.getDoorValue());
      }
      if (other.getIsLocked() != false) {
        setIsLocked(other.getIsLocked());
      }
      if (other.getIsOpen() != false) {
        setIsOpen(other.getIsOpen());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              door_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              isLocked_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              isOpen_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int door_ = 0;
    /**
     * <code>.sdv.services.locking.Door door = 1;</code>
     * @return The enum numeric value on the wire for door.
     */
    @java.lang.Override public int getDoorValue() {
      return door_;
    }
    /**
     * <code>.sdv.services.locking.Door door = 1;</code>
     * @param value The enum numeric value on the wire for door to set.
     * @return This builder for chaining.
     */
    public Builder setDoorValue(int value) {
      door_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.sdv.services.locking.Door door = 1;</code>
     * @return The door.
     */
    @java.lang.Override
    public sdv.services.locking.Door getDoor() {
      sdv.services.locking.Door result = sdv.services.locking.Door.forNumber(door_);
      return result == null ? sdv.services.locking.Door.UNRECOGNIZED : result;
    }
    /**
     * <code>.sdv.services.locking.Door door = 1;</code>
     * @param value The door to set.
     * @return This builder for chaining.
     */
    public Builder setDoor(sdv.services.locking.Door value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      door_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.sdv.services.locking.Door door = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDoor() {
      bitField0_ = (bitField0_ & ~0x00000001);
      door_ = 0;
      onChanged();
      return this;
    }

    private boolean isLocked_ ;
    /**
     * <code>bool is_locked = 2;</code>
     * @return The isLocked.
     */
    @java.lang.Override
    public boolean getIsLocked() {
      return isLocked_;
    }
    /**
     * <code>bool is_locked = 2;</code>
     * @param value The isLocked to set.
     * @return This builder for chaining.
     */
    public Builder setIsLocked(boolean value) {

      isLocked_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_locked = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsLocked() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isLocked_ = false;
      onChanged();
      return this;
    }

    private boolean isOpen_ ;
    /**
     * <code>bool is_open = 3;</code>
     * @return The isOpen.
     */
    @java.lang.Override
    public boolean getIsOpen() {
      return isOpen_;
    }
    /**
     * <code>bool is_open = 3;</code>
     * @param value The isOpen to set.
     * @return This builder for chaining.
     */
    public Builder setIsOpen(boolean value) {

      isOpen_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_open = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsOpen() {
      bitField0_ = (bitField0_ & ~0x00000004);
      isOpen_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sdv.services.locking.GetLockStateResponse)
  }

  // @@protoc_insertion_point(class_scope:sdv.services.locking.GetLockStateResponse)
  private static final sdv.services.locking.GetLockStateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sdv.services.locking.GetLockStateResponse();
  }

  public static sdv.services.locking.GetLockStateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLockStateResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetLockStateResponse>() {
    @java.lang.Override
    public GetLockStateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetLockStateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetLockStateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sdv.services.locking.GetLockStateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

