// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/locking_service.proto
// Protobuf Java Version: 4.33.4

package sdv.services.locking;

@com.google.protobuf.Generated
public interface GetLockStateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdv.services.locking.GetLockStateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sdv.services.locking.Door door = 1;</code>
   * @return The enum numeric value on the wire for door.
   */
  int getDoorValue();
  /**
   * <code>.sdv.services.locking.Door door = 1;</code>
   * @return The door.
   */
  sdv.services.locking.Door getDoor();
}
