// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/locking_service.proto
// Protobuf Java Version: 4.33.4

package sdv.services.locking;

@com.google.protobuf.Generated
public interface LockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdv.services.locking.LockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sdv.services.locking.Door door = 1;</code>
   * @return The enum numeric value on the wire for door.
   */
  int getDoorValue();
  /**
   * <code>.sdv.services.locking.Door door = 1;</code>
   * @return The door.
   */
  sdv.services.locking.Door getDoor();

  /**
   * <code>string command_id = 2;</code>
   * @return The commandId.
   */
  java.lang.String getCommandId();
  /**
   * <code>string command_id = 2;</code>
   * @return The bytes for commandId.
   */
  com.google.protobuf.ByteString
      getCommandIdBytes();

  /**
   * <code>string auth_token = 3;</code>
   * @return The authToken.
   */
  java.lang.String getAuthToken();
  /**
   * <code>string auth_token = 3;</code>
   * @return The bytes for authToken.
   */
  com.google.protobuf.ByteString
      getAuthTokenBytes();
}
