// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/locking_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package sdv.services.locking;

@kotlin.jvm.JvmName("-initializelockRequest")
public inline fun lockRequest(block: sdv.services.locking.LockRequestKt.Dsl.() -> kotlin.Unit): sdv.services.locking.LockRequest =
  sdv.services.locking.LockRequestKt.Dsl._create(sdv.services.locking.LockRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `sdv.services.locking.LockRequest`
 */
public object LockRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: sdv.services.locking.LockRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: sdv.services.locking.LockRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): sdv.services.locking.LockRequest = _builder.build()

    /**
     * `.sdv.services.locking.Door door = 1;`
     */
    public var door: sdv.services.locking.Door
      @kotlin.jvm.JvmName("getDoor")
        get() = _builder.door
      @kotlin.jvm.JvmName("setDoor")
        set(value) {
        _builder.door = value
      }
    public var doorValue: kotlin.Int
      @kotlin.jvm.JvmName("getDoorValue")
        get() = _builder.doorValue
      @kotlin.jvm.JvmName("setDoorValue")
        set(value) {
        _builder.doorValue = value
      }
    /**
     * `.sdv.services.locking.Door door = 1;`
     */
    public fun clearDoor() {
      _builder.clearDoor()
    }

    /**
     * `string command_id = 2;`
     */
    public var commandId: kotlin.String
      @kotlin.jvm.JvmName("getCommandId")
        get() = _builder.commandId
      @kotlin.jvm.JvmName("setCommandId")
        set(value) {
        _builder.commandId = value
      }
    /**
     * `string command_id = 2;`
     */
    public fun clearCommandId() {
      _builder.clearCommandId()
    }

    /**
     * `string auth_token = 3;`
     */
    public var authToken: kotlin.String
      @kotlin.jvm.JvmName("getAuthToken")
        get() = _builder.authToken
      @kotlin.jvm.JvmName("setAuthToken")
        set(value) {
        _builder.authToken = value
      }
    /**
     * `string auth_token = 3;`
     */
    public fun clearAuthToken() {
      _builder.clearAuthToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun sdv.services.locking.LockRequest.copy(block: `sdv.services.locking`.LockRequestKt.Dsl.() -> kotlin.Unit): sdv.services.locking.LockRequest =
  `sdv.services.locking`.LockRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

