// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vss/signals.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package sdv.vss;

@kotlin.jvm.JvmName("-initializeparkingState")
public inline fun parkingState(block: sdv.vss.ParkingStateKt.Dsl.() -> kotlin.Unit): sdv.vss.Signals.ParkingState =
  sdv.vss.ParkingStateKt.Dsl._create(sdv.vss.Signals.ParkingState.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `sdv.vss.ParkingState`
 */
public object ParkingStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: sdv.vss.Signals.ParkingState.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: sdv.vss.Signals.ParkingState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): sdv.vss.Signals.ParkingState = _builder.build()

    /**
     * `bool session_active = 1;`
     */
    public var sessionActive: kotlin.Boolean
      @kotlin.jvm.JvmName("getSessionActive")
        get() = _builder.sessionActive
      @kotlin.jvm.JvmName("setSessionActive")
        set(value) {
        _builder.sessionActive = value
      }
    /**
     * `bool session_active = 1;`
     */
    public fun clearSessionActive() {
      _builder.clearSessionActive()
    }

    /**
     * `string session_id = 2;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * `string session_id = 2;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val ParkingStateKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun sdv.vss.Signals.ParkingState.copy(block: `sdv.vss`.ParkingStateKt.Dsl.() -> kotlin.Unit): sdv.vss.Signals.ParkingState =
  `sdv.vss`.ParkingStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val sdv.vss.Signals.ParkingStateOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

