// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vss/signals.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package sdv.vss;

@kotlin.jvm.JvmName("-initializevehicleSpeed")
public inline fun vehicleSpeed(block: sdv.vss.VehicleSpeedKt.Dsl.() -> kotlin.Unit): sdv.vss.Signals.VehicleSpeed =
  sdv.vss.VehicleSpeedKt.Dsl._create(sdv.vss.Signals.VehicleSpeed.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `sdv.vss.VehicleSpeed`
 */
public object VehicleSpeedKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: sdv.vss.Signals.VehicleSpeed.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: sdv.vss.Signals.VehicleSpeed.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): sdv.vss.Signals.VehicleSpeed = _builder.build()

    /**
     * `float speed_kmh = 1;`
     */
    public var speedKmh: kotlin.Float
      @kotlin.jvm.JvmName("getSpeedKmh")
        get() = _builder.speedKmh
      @kotlin.jvm.JvmName("setSpeedKmh")
        set(value) {
        _builder.speedKmh = value
      }
    /**
     * `float speed_kmh = 1;`
     */
    public fun clearSpeedKmh() {
      _builder.clearSpeedKmh()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val VehicleSpeedKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun sdv.vss.Signals.VehicleSpeed.copy(block: `sdv.vss`.VehicleSpeedKt.Dsl.() -> kotlin.Unit): sdv.vss.Signals.VehicleSpeed =
  `sdv.vss`.VehicleSpeedKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val sdv.vss.Signals.VehicleSpeedOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

