.PHONY: build build-rust build-go test test-rust test-go test-setup check clean lint proto infra-up infra-down

# Build all components
build: build-rust build-go

build-rust:
	cd rhivos && cargo build --workspace

build-go:
	cd backend/parking-fee-service && go build ./...
	cd backend/cloud-gateway && go build ./...
	cd mock/parking-app-cli && go build ./...
	cd mock/companion-app-cli && go build ./...
	cd mock/parking-operator && go build ./...

# Lint all code
lint:
	cd rhivos && cargo clippy --workspace -- -D warnings
	cd backend/parking-fee-service && go vet ./...
	cd backend/cloud-gateway && go vet ./...
	cd mock/parking-app-cli && go vet ./...
	cd mock/companion-app-cli && go vet ./...
	cd mock/parking-operator && go vet ./...
	cd tests/setup && go vet ./...
	cd tests/mock-apps && go vet ./...
	cd tests/databroker && go vet ./...

# Run tests (only modules whose tests currently pass)
test: test-rust test-go

test-rust:
	cd rhivos && cargo test --workspace --exclude cloud-gateway-client --exclude update-service --exclude parking-operator-adaptor

test-go:
	cd backend/parking-fee-service && go test .
	cd backend/cloud-gateway && go test .
	cd mock/parking-app-cli && go test ./...
	cd mock/companion-app-cli && go test ./...
	cd mock/parking-operator && go test ./...
	cd tests/mock-apps && go test ./...

# Run setup verification tests
test-setup:
	cd tests/setup && go test -v ./...

# Quality gate: lint + compile all tests
check: lint
	cd rhivos && cargo test --workspace --no-run
	cd backend/parking-fee-service && go test -c -o /dev/null ./...
	cd backend/cloud-gateway && go test -c -o /dev/null ./...
	cd mock/parking-app-cli && go test -c -o /dev/null ./...
	cd mock/companion-app-cli && go test -c -o /dev/null ./...
	cd mock/parking-operator && go test -c -o /dev/null ./...
	cd tests/mock-apps && go test -c -o /dev/null ./...
	cd tests/setup && go test -c -o /dev/null ./...
	cd tests/databroker && go test -c -o /dev/null ./...

# Remove build artifacts
clean:
	cd rhivos && cargo clean
	cd backend/parking-fee-service && go clean ./...
	cd backend/cloud-gateway && go clean ./...
	cd mock/parking-app-cli && go clean ./...
	cd mock/companion-app-cli && go clean ./...
	cd mock/parking-operator && go clean ./...

# Generate Go code from proto definitions
proto:
	@command -v protoc >/dev/null 2>&1 || { echo "Error: protoc is required but not installed. Install protoc and protoc-gen-go." >&2; exit 1; }
	protoc --proto_path=proto --go_out=gen --go-grpc_out=gen $$(find proto -name '*.proto')

# Start local infrastructure (NATS + Kuksa Databroker)
infra-up:
	mkdir -p /tmp/kuksa
	podman-compose -f deployments/compose.yml up -d

# Stop local infrastructure
infra-down:
	podman-compose -f deployments/compose.yml down
