// Minimal Kuksa Databroker v2 VAL service — used by integration tests.
// Based on the official kuksa.val.v2 proto specification.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: kuksa/val/v2/val.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetValueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the requested signal.
	SignalId      *SignalID `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_kuksa_val_v2_val_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v2_val_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v2_val_proto_rawDescGZIP(), []int{0}
}

func (x *GetValueRequest) GetSignalId() *SignalID {
	if x != nil {
		return x.SignalId
	}
	return nil
}

type GetValueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The latest datapoint for the requested signal.
	DataPoint     *DataPoint `protobuf:"bytes,1,opt,name=data_point,json=dataPoint,proto3" json:"data_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	mi := &file_kuksa_val_v2_val_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v2_val_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v2_val_proto_rawDescGZIP(), []int{1}
}

func (x *GetValueResponse) GetDataPoint() *DataPoint {
	if x != nil {
		return x.DataPoint
	}
	return nil
}

// Identifies a signal either by numeric ID or by VSS path string.
type SignalID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Signal:
	//
	//	*SignalID_Id
	//	*SignalID_Path
	Signal        isSignalID_Signal `protobuf_oneof:"signal"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalID) Reset() {
	*x = SignalID{}
	mi := &file_kuksa_val_v2_val_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalID) ProtoMessage() {}

func (x *SignalID) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v2_val_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalID.ProtoReflect.Descriptor instead.
func (*SignalID) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v2_val_proto_rawDescGZIP(), []int{2}
}

func (x *SignalID) GetSignal() isSignalID_Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *SignalID) GetId() uint32 {
	if x != nil {
		if x, ok := x.Signal.(*SignalID_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *SignalID) GetPath() string {
	if x != nil {
		if x, ok := x.Signal.(*SignalID_Path); ok {
			return x.Path
		}
	}
	return ""
}

type isSignalID_Signal interface {
	isSignalID_Signal()
}

type SignalID_Id struct {
	// Numeric (internal) ID assigned by the databroker.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type SignalID_Path struct {
	// VSS path string (e.g. "Vehicle.Speed").
	Path string `protobuf:"bytes,2,opt,name=path,proto3,oneof"`
}

func (*SignalID_Id) isSignalID_Signal() {}

func (*SignalID_Path) isSignalID_Signal() {}

// A single signal value at a point in time.
type DataPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signal value.
	Value         *Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_kuksa_val_v2_val_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v2_val_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v2_val_proto_rawDescGZIP(), []int{3}
}

func (x *DataPoint) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Typed value of a VSS signal.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TypedValue:
	//
	//	*Value_String_
	//	*Value_Bool
	//	*Value_Int32
	//	*Value_Int64
	//	*Value_Uint32
	//	*Value_Uint64
	//	*Value_Float
	//	*Value_Double
	TypedValue    isValue_TypedValue `protobuf_oneof:"typed_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_kuksa_val_v2_val_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_kuksa_val_v2_val_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_kuksa_val_v2_val_proto_rawDescGZIP(), []int{4}
}

func (x *Value) GetTypedValue() isValue_TypedValue {
	if x != nil {
		return x.TypedValue
	}
	return nil
}

func (x *Value) GetString_() string {
	if x != nil {
		if x, ok := x.TypedValue.(*Value_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *Value) GetBool() bool {
	if x != nil {
		if x, ok := x.TypedValue.(*Value_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *Value) GetInt32() int32 {
	if x != nil {
		if x, ok := x.TypedValue.(*Value_Int32); ok {
			return x.Int32
		}
	}
	return 0
}

func (x *Value) GetInt64() int64 {
	if x != nil {
		if x, ok := x.TypedValue.(*Value_Int64); ok {
			return x.Int64
		}
	}
	return 0
}

func (x *Value) GetUint32() uint32 {
	if x != nil {
		if x, ok := x.TypedValue.(*Value_Uint32); ok {
			return x.Uint32
		}
	}
	return 0
}

func (x *Value) GetUint64() uint64 {
	if x != nil {
		if x, ok := x.TypedValue.(*Value_Uint64); ok {
			return x.Uint64
		}
	}
	return 0
}

func (x *Value) GetFloat() float32 {
	if x != nil {
		if x, ok := x.TypedValue.(*Value_Float); ok {
			return x.Float
		}
	}
	return 0
}

func (x *Value) GetDouble() float64 {
	if x != nil {
		if x, ok := x.TypedValue.(*Value_Double); ok {
			return x.Double
		}
	}
	return 0
}

type isValue_TypedValue interface {
	isValue_TypedValue()
}

type Value_String_ struct {
	String_ string `protobuf:"bytes,11,opt,name=string,proto3,oneof"`
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,12,opt,name=bool,proto3,oneof"`
}

type Value_Int32 struct {
	Int32 int32 `protobuf:"varint,13,opt,name=int32,proto3,oneof"`
}

type Value_Int64 struct {
	Int64 int64 `protobuf:"varint,14,opt,name=int64,proto3,oneof"`
}

type Value_Uint32 struct {
	Uint32 uint32 `protobuf:"varint,15,opt,name=uint32,proto3,oneof"`
}

type Value_Uint64 struct {
	Uint64 uint64 `protobuf:"varint,16,opt,name=uint64,proto3,oneof"`
}

type Value_Float struct {
	Float float32 `protobuf:"fixed32,17,opt,name=float,proto3,oneof"`
}

type Value_Double struct {
	Double float64 `protobuf:"fixed64,18,opt,name=double,proto3,oneof"`
}

func (*Value_String_) isValue_TypedValue() {}

func (*Value_Bool) isValue_TypedValue() {}

func (*Value_Int32) isValue_TypedValue() {}

func (*Value_Int64) isValue_TypedValue() {}

func (*Value_Uint32) isValue_TypedValue() {}

func (*Value_Uint64) isValue_TypedValue() {}

func (*Value_Float) isValue_TypedValue() {}

func (*Value_Double) isValue_TypedValue() {}

var File_kuksa_val_v2_val_proto protoreflect.FileDescriptor

const file_kuksa_val_v2_val_proto_rawDesc = "" +
	"\n" +
	"\x16kuksa/val/v2/val.proto\x12\fkuksa.val.v2\"F\n" +
	"\x0fGetValueRequest\x123\n" +
	"\tsignal_id\x18\x01 \x01(\v2\x16.kuksa.val.v2.SignalIDR\bsignalId\"J\n" +
	"\x10GetValueResponse\x126\n" +
	"\n" +
	"data_point\x18\x01 \x01(\v2\x17.kuksa.val.v2.DataPointR\tdataPoint\"<\n" +
	"\bSignalID\x12\x10\n" +
	"\x02id\x18\x01 \x01(\rH\x00R\x02id\x12\x14\n" +
	"\x04path\x18\x02 \x01(\tH\x00R\x04pathB\b\n" +
	"\x06signal\"6\n" +
	"\tDataPoint\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.kuksa.val.v2.ValueR\x05value\"\xdc\x01\n" +
	"\x05Value\x12\x18\n" +
	"\x06string\x18\v \x01(\tH\x00R\x06string\x12\x14\n" +
	"\x04bool\x18\f \x01(\bH\x00R\x04bool\x12\x16\n" +
	"\x05int32\x18\r \x01(\x05H\x00R\x05int32\x12\x16\n" +
	"\x05int64\x18\x0e \x01(\x03H\x00R\x05int64\x12\x18\n" +
	"\x06uint32\x18\x0f \x01(\rH\x00R\x06uint32\x12\x18\n" +
	"\x06uint64\x18\x10 \x01(\x04H\x00R\x06uint64\x12\x16\n" +
	"\x05float\x18\x11 \x01(\x02H\x00R\x05float\x12\x18\n" +
	"\x06double\x18\x12 \x01(\x01H\x00R\x06doubleB\r\n" +
	"\vtyped_value2P\n" +
	"\x03VAL\x12I\n" +
	"\bGetValue\x12\x1d.kuksa.val.v2.GetValueRequest\x1a\x1e.kuksa.val.v2.GetValueResponseB3Z1github.com/parking-fee-service/proto/kuksa/val/v2b\x06proto3"

var (
	file_kuksa_val_v2_val_proto_rawDescOnce sync.Once
	file_kuksa_val_v2_val_proto_rawDescData []byte
)

func file_kuksa_val_v2_val_proto_rawDescGZIP() []byte {
	file_kuksa_val_v2_val_proto_rawDescOnce.Do(func() {
		file_kuksa_val_v2_val_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kuksa_val_v2_val_proto_rawDesc), len(file_kuksa_val_v2_val_proto_rawDesc)))
	})
	return file_kuksa_val_v2_val_proto_rawDescData
}

var file_kuksa_val_v2_val_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kuksa_val_v2_val_proto_goTypes = []any{
	(*GetValueRequest)(nil),  // 0: kuksa.val.v2.GetValueRequest
	(*GetValueResponse)(nil), // 1: kuksa.val.v2.GetValueResponse
	(*SignalID)(nil),         // 2: kuksa.val.v2.SignalID
	(*DataPoint)(nil),        // 3: kuksa.val.v2.DataPoint
	(*Value)(nil),            // 4: kuksa.val.v2.Value
}
var file_kuksa_val_v2_val_proto_depIdxs = []int32{
	2, // 0: kuksa.val.v2.GetValueRequest.signal_id:type_name -> kuksa.val.v2.SignalID
	3, // 1: kuksa.val.v2.GetValueResponse.data_point:type_name -> kuksa.val.v2.DataPoint
	4, // 2: kuksa.val.v2.DataPoint.value:type_name -> kuksa.val.v2.Value
	0, // 3: kuksa.val.v2.VAL.GetValue:input_type -> kuksa.val.v2.GetValueRequest
	1, // 4: kuksa.val.v2.VAL.GetValue:output_type -> kuksa.val.v2.GetValueResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kuksa_val_v2_val_proto_init() }
func file_kuksa_val_v2_val_proto_init() {
	if File_kuksa_val_v2_val_proto != nil {
		return
	}
	file_kuksa_val_v2_val_proto_msgTypes[2].OneofWrappers = []any{
		(*SignalID_Id)(nil),
		(*SignalID_Path)(nil),
	}
	file_kuksa_val_v2_val_proto_msgTypes[4].OneofWrappers = []any{
		(*Value_String_)(nil),
		(*Value_Bool)(nil),
		(*Value_Int32)(nil),
		(*Value_Int64)(nil),
		(*Value_Uint32)(nil),
		(*Value_Uint64)(nil),
		(*Value_Float)(nil),
		(*Value_Double)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kuksa_val_v2_val_proto_rawDesc), len(file_kuksa_val_v2_val_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kuksa_val_v2_val_proto_goTypes,
		DependencyIndexes: file_kuksa_val_v2_val_proto_depIdxs,
		MessageInfos:      file_kuksa_val_v2_val_proto_msgTypes,
	}.Build()
	File_kuksa_val_v2_val_proto = out.File
	file_kuksa_val_v2_val_proto_goTypes = nil
	file_kuksa_val_v2_val_proto_depIdxs = nil
}
