// Minimal Kuksa Databroker v2 VAL service — used by integration tests.
// Based on the official kuksa.val.v2 proto specification.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: kuksa/val/v2/val.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VAL_GetValue_FullMethodName = "/kuksa.val.v2.VAL/GetValue"
)

// VALClient is the client API for VAL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Vehicle Abstraction Layer v2 — the Kuksa Databroker gRPC service.
type VALClient interface {
	// Get the latest value of a single signal.
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
}

type vALClient struct {
	cc grpc.ClientConnInterface
}

func NewVALClient(cc grpc.ClientConnInterface) VALClient {
	return &vALClient{cc}
}

func (c *vALClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, VAL_GetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VALServer is the server API for VAL service.
// All implementations must embed UnimplementedVALServer
// for forward compatibility.
//
// Vehicle Abstraction Layer v2 — the Kuksa Databroker gRPC service.
type VALServer interface {
	// Get the latest value of a single signal.
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	mustEmbedUnimplementedVALServer()
}

// UnimplementedVALServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVALServer struct{}

func (UnimplementedVALServer) GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedVALServer) mustEmbedUnimplementedVALServer() {}
func (UnimplementedVALServer) testEmbeddedByValue()             {}

// UnsafeVALServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VALServer will
// result in compilation errors.
type UnsafeVALServer interface {
	mustEmbedUnimplementedVALServer()
}

func RegisterVALServer(s grpc.ServiceRegistrar, srv VALServer) {
	// If the following call panics, it indicates UnimplementedVALServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VAL_ServiceDesc, srv)
}

func _VAL_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VALServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VAL_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VALServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VAL_ServiceDesc is the grpc.ServiceDesc for VAL service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VAL_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kuksa.val.v2.VAL",
	HandlerType: (*VALServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValue",
			Handler:    _VAL_GetValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kuksa/val/v2/val.proto",
}
