//*******************************************************************************
// Copyright (c) 2024 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License 2.0 which is available at
// http://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
//******************************************************************************

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: kuksa/val/v2/val.proto

package kuksavalv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VAL_GetValue_FullMethodName           = "/kuksa.val.v2.VAL/GetValue"
	VAL_GetValues_FullMethodName          = "/kuksa.val.v2.VAL/GetValues"
	VAL_Subscribe_FullMethodName          = "/kuksa.val.v2.VAL/Subscribe"
	VAL_SubscribeById_FullMethodName      = "/kuksa.val.v2.VAL/SubscribeById"
	VAL_Actuate_FullMethodName            = "/kuksa.val.v2.VAL/Actuate"
	VAL_BatchActuate_FullMethodName       = "/kuksa.val.v2.VAL/BatchActuate"
	VAL_ListMetadata_FullMethodName       = "/kuksa.val.v2.VAL/ListMetadata"
	VAL_PublishValue_FullMethodName       = "/kuksa.val.v2.VAL/PublishValue"
	VAL_OpenProviderStream_FullMethodName = "/kuksa.val.v2.VAL/OpenProviderStream"
	VAL_GetServerInfo_FullMethodName      = "/kuksa.val.v2.VAL/GetServerInfo"
)

// VALClient is the client API for VAL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VALClient interface {
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	GetValues(ctx context.Context, in *GetValuesRequest, opts ...grpc.CallOption) (*GetValuesResponse, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
	SubscribeById(ctx context.Context, in *SubscribeByIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeByIdResponse], error)
	Actuate(ctx context.Context, in *ActuateRequest, opts ...grpc.CallOption) (*ActuateResponse, error)
	BatchActuate(ctx context.Context, in *BatchActuateRequest, opts ...grpc.CallOption) (*BatchActuateResponse, error)
	ListMetadata(ctx context.Context, in *ListMetadataRequest, opts ...grpc.CallOption) (*ListMetadataResponse, error)
	PublishValue(ctx context.Context, in *PublishValueRequest, opts ...grpc.CallOption) (*PublishValueResponse, error)
	OpenProviderStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OpenProviderStreamRequest, OpenProviderStreamResponse], error)
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
}

type vALClient struct {
	cc grpc.ClientConnInterface
}

func NewVALClient(cc grpc.ClientConnInterface) VALClient {
	return &vALClient{cc}
}

func (c *vALClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, VAL_GetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vALClient) GetValues(ctx context.Context, in *GetValuesRequest, opts ...grpc.CallOption) (*GetValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValuesResponse)
	err := c.cc.Invoke(ctx, VAL_GetValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vALClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VAL_ServiceDesc.Streams[0], VAL_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VAL_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

func (c *vALClient) SubscribeById(ctx context.Context, in *SubscribeByIdRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeByIdResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VAL_ServiceDesc.Streams[1], VAL_SubscribeById_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeByIdRequest, SubscribeByIdResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VAL_SubscribeByIdClient = grpc.ServerStreamingClient[SubscribeByIdResponse]

func (c *vALClient) Actuate(ctx context.Context, in *ActuateRequest, opts ...grpc.CallOption) (*ActuateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActuateResponse)
	err := c.cc.Invoke(ctx, VAL_Actuate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vALClient) BatchActuate(ctx context.Context, in *BatchActuateRequest, opts ...grpc.CallOption) (*BatchActuateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchActuateResponse)
	err := c.cc.Invoke(ctx, VAL_BatchActuate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vALClient) ListMetadata(ctx context.Context, in *ListMetadataRequest, opts ...grpc.CallOption) (*ListMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMetadataResponse)
	err := c.cc.Invoke(ctx, VAL_ListMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vALClient) PublishValue(ctx context.Context, in *PublishValueRequest, opts ...grpc.CallOption) (*PublishValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishValueResponse)
	err := c.cc.Invoke(ctx, VAL_PublishValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vALClient) OpenProviderStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OpenProviderStreamRequest, OpenProviderStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VAL_ServiceDesc.Streams[2], VAL_OpenProviderStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenProviderStreamRequest, OpenProviderStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VAL_OpenProviderStreamClient = grpc.BidiStreamingClient[OpenProviderStreamRequest, OpenProviderStreamResponse]

func (c *vALClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, VAL_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VALServer is the server API for VAL service.
// All implementations must embed UnimplementedVALServer
// for forward compatibility.
type VALServer interface {
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	GetValues(context.Context, *GetValuesRequest) (*GetValuesResponse, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	SubscribeById(*SubscribeByIdRequest, grpc.ServerStreamingServer[SubscribeByIdResponse]) error
	Actuate(context.Context, *ActuateRequest) (*ActuateResponse, error)
	BatchActuate(context.Context, *BatchActuateRequest) (*BatchActuateResponse, error)
	ListMetadata(context.Context, *ListMetadataRequest) (*ListMetadataResponse, error)
	PublishValue(context.Context, *PublishValueRequest) (*PublishValueResponse, error)
	OpenProviderStream(grpc.BidiStreamingServer[OpenProviderStreamRequest, OpenProviderStreamResponse]) error
	GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error)
	mustEmbedUnimplementedVALServer()
}

// UnimplementedVALServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVALServer struct{}

func (UnimplementedVALServer) GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedVALServer) GetValues(context.Context, *GetValuesRequest) (*GetValuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValues not implemented")
}
func (UnimplementedVALServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedVALServer) SubscribeById(*SubscribeByIdRequest, grpc.ServerStreamingServer[SubscribeByIdResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeById not implemented")
}
func (UnimplementedVALServer) Actuate(context.Context, *ActuateRequest) (*ActuateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Actuate not implemented")
}
func (UnimplementedVALServer) BatchActuate(context.Context, *BatchActuateRequest) (*BatchActuateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchActuate not implemented")
}
func (UnimplementedVALServer) ListMetadata(context.Context, *ListMetadataRequest) (*ListMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMetadata not implemented")
}
func (UnimplementedVALServer) PublishValue(context.Context, *PublishValueRequest) (*PublishValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishValue not implemented")
}
func (UnimplementedVALServer) OpenProviderStream(grpc.BidiStreamingServer[OpenProviderStreamRequest, OpenProviderStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method OpenProviderStream not implemented")
}
func (UnimplementedVALServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedVALServer) mustEmbedUnimplementedVALServer() {}
func (UnimplementedVALServer) testEmbeddedByValue()             {}

// UnsafeVALServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VALServer will
// result in compilation errors.
type UnsafeVALServer interface {
	mustEmbedUnimplementedVALServer()
}

func RegisterVALServer(s grpc.ServiceRegistrar, srv VALServer) {
	// If the following call panics, it indicates UnimplementedVALServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VAL_ServiceDesc, srv)
}

func _VAL_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VALServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VAL_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VALServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VAL_GetValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VALServer).GetValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VAL_GetValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VALServer).GetValues(ctx, req.(*GetValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VAL_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VALServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VAL_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

func _VAL_SubscribeById_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeByIdRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VALServer).SubscribeById(m, &grpc.GenericServerStream[SubscribeByIdRequest, SubscribeByIdResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VAL_SubscribeByIdServer = grpc.ServerStreamingServer[SubscribeByIdResponse]

func _VAL_Actuate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActuateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VALServer).Actuate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VAL_Actuate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VALServer).Actuate(ctx, req.(*ActuateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VAL_BatchActuate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchActuateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VALServer).BatchActuate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VAL_BatchActuate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VALServer).BatchActuate(ctx, req.(*BatchActuateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VAL_ListMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VALServer).ListMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VAL_ListMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VALServer).ListMetadata(ctx, req.(*ListMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VAL_PublishValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VALServer).PublishValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VAL_PublishValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VALServer).PublishValue(ctx, req.(*PublishValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VAL_OpenProviderStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VALServer).OpenProviderStream(&grpc.GenericServerStream[OpenProviderStreamRequest, OpenProviderStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VAL_OpenProviderStreamServer = grpc.BidiStreamingServer[OpenProviderStreamRequest, OpenProviderStreamResponse]

func _VAL_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VALServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VAL_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VALServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VAL_ServiceDesc is the grpc.ServiceDesc for VAL service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VAL_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kuksa.val.v2.VAL",
	HandlerType: (*VALServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValue",
			Handler:    _VAL_GetValue_Handler,
		},
		{
			MethodName: "GetValues",
			Handler:    _VAL_GetValues_Handler,
		},
		{
			MethodName: "Actuate",
			Handler:    _VAL_Actuate_Handler,
		},
		{
			MethodName: "BatchActuate",
			Handler:    _VAL_BatchActuate_Handler,
		},
		{
			MethodName: "ListMetadata",
			Handler:    _VAL_ListMetadata_Handler,
		},
		{
			MethodName: "PublishValue",
			Handler:    _VAL_PublishValue_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _VAL_GetServerInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _VAL_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeById",
			Handler:       _VAL_SubscribeById_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OpenProviderStream",
			Handler:       _VAL_OpenProviderStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "kuksa/val/v2/val.proto",
}
