// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/parking_adaptor.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package sdv.services.parking;

@kotlin.jvm.JvmName("-initializegetSessionStatusRequest")
public inline fun getSessionStatusRequest(block: sdv.services.parking.GetSessionStatusRequestKt.Dsl.() -> kotlin.Unit): sdv.services.parking.GetSessionStatusRequest =
  sdv.services.parking.GetSessionStatusRequestKt.Dsl._create(sdv.services.parking.GetSessionStatusRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Request to get session status.
 * ```
 *
 * Protobuf type `sdv.services.parking.GetSessionStatusRequest`
 */
public object GetSessionStatusRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: sdv.services.parking.GetSessionStatusRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: sdv.services.parking.GetSessionStatusRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): sdv.services.parking.GetSessionStatusRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun sdv.services.parking.GetSessionStatusRequest.copy(block: `sdv.services.parking`.GetSessionStatusRequestKt.Dsl.() -> kotlin.Unit): sdv.services.parking.GetSessionStatusRequest =
  `sdv.services.parking`.GetSessionStatusRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

