// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/parking_adaptor.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package sdv.services.parking;

@kotlin.jvm.JvmName("-initializegetSessionStatusResponse")
public inline fun getSessionStatusResponse(block: sdv.services.parking.GetSessionStatusResponseKt.Dsl.() -> kotlin.Unit): sdv.services.parking.GetSessionStatusResponse =
  sdv.services.parking.GetSessionStatusResponseKt.Dsl._create(sdv.services.parking.GetSessionStatusResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * Response with session status information.
 * ```
 *
 * Protobuf type `sdv.services.parking.GetSessionStatusResponse`
 */
public object GetSessionStatusResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: sdv.services.parking.GetSessionStatusResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: sdv.services.parking.GetSessionStatusResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): sdv.services.parking.GetSessionStatusResponse = _builder.build()

    /**
     * ```
     * Whether there is an active session
     * ```
     *
     * `bool has_active_session = 1;`
     */
    public var hasActiveSession: kotlin.Boolean
      @kotlin.jvm.JvmName("getHasActiveSession")
        get() = _builder.hasActiveSession
      @kotlin.jvm.JvmName("setHasActiveSession")
        set(value) {
        _builder.hasActiveSession = value
      }
    /**
     * ```
     * Whether there is an active session
     * ```
     *
     * `bool has_active_session = 1;`
     */
    public fun clearHasActiveSession() {
      _builder.clearHasActiveSession()
    }

    /**
     * ```
     * Session ID (empty if no session)
     * ```
     *
     * `string session_id = 2;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * ```
     * Session ID (empty if no session)
     * ```
     *
     * `string session_id = 2;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * ```
     * Current session state
     * ```
     *
     * `.sdv.services.parking.SessionState state = 3;`
     */
    public var state: sdv.services.parking.SessionState
      @kotlin.jvm.JvmName("getState")
        get() = _builder.state
      @kotlin.jvm.JvmName("setState")
        set(value) {
        _builder.state = value
      }
    public var stateValue: kotlin.Int
      @kotlin.jvm.JvmName("getStateValue")
        get() = _builder.stateValue
      @kotlin.jvm.JvmName("setStateValue")
        set(value) {
        _builder.stateValue = value
      }
    /**
     * ```
     * Current session state
     * ```
     *
     * `.sdv.services.parking.SessionState state = 3;`
     */
    public fun clearState() {
      _builder.clearState()
    }

    /**
     * ```
     * Session start time as Unix timestamp
     * ```
     *
     * `int64 start_time_unix = 4;`
     */
    public var startTimeUnix: kotlin.Long
      @kotlin.jvm.JvmName("getStartTimeUnix")
        get() = _builder.startTimeUnix
      @kotlin.jvm.JvmName("setStartTimeUnix")
        set(value) {
        _builder.startTimeUnix = value
      }
    /**
     * ```
     * Session start time as Unix timestamp
     * ```
     *
     * `int64 start_time_unix = 4;`
     */
    public fun clearStartTimeUnix() {
      _builder.clearStartTimeUnix()
    }

    /**
     * ```
     * Duration of the session in seconds
     * ```
     *
     * `int64 duration_seconds = 5;`
     */
    public var durationSeconds: kotlin.Long
      @kotlin.jvm.JvmName("getDurationSeconds")
        get() = _builder.durationSeconds
      @kotlin.jvm.JvmName("setDurationSeconds")
        set(value) {
        _builder.durationSeconds = value
      }
    /**
     * ```
     * Duration of the session in seconds
     * ```
     *
     * `int64 duration_seconds = 5;`
     */
    public fun clearDurationSeconds() {
      _builder.clearDurationSeconds()
    }

    /**
     * ```
     * Current cost of the session
     * ```
     *
     * `double current_cost = 6;`
     */
    public var currentCost: kotlin.Double
      @kotlin.jvm.JvmName("getCurrentCost")
        get() = _builder.currentCost
      @kotlin.jvm.JvmName("setCurrentCost")
        set(value) {
        _builder.currentCost = value
      }
    /**
     * ```
     * Current cost of the session
     * ```
     *
     * `double current_cost = 6;`
     */
    public fun clearCurrentCost() {
      _builder.clearCurrentCost()
    }

    /**
     * ```
     * Zone ID where parked
     * ```
     *
     * `string zone_id = 7;`
     */
    public var zoneId: kotlin.String
      @kotlin.jvm.JvmName("getZoneId")
        get() = _builder.zoneId
      @kotlin.jvm.JvmName("setZoneId")
        set(value) {
        _builder.zoneId = value
      }
    /**
     * ```
     * Zone ID where parked
     * ```
     *
     * `string zone_id = 7;`
     */
    public fun clearZoneId() {
      _builder.clearZoneId()
    }

    /**
     * ```
     * Error message if state is ERROR
     * ```
     *
     * `string error_message = 8;`
     */
    public var errorMessage: kotlin.String
      @kotlin.jvm.JvmName("getErrorMessage")
        get() = _builder.errorMessage
      @kotlin.jvm.JvmName("setErrorMessage")
        set(value) {
        _builder.errorMessage = value
      }
    /**
     * ```
     * Error message if state is ERROR
     * ```
     *
     * `string error_message = 8;`
     */
    public fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }

    /**
     * ```
     * Latitude where session started
     * ```
     *
     * `double latitude = 9;`
     */
    public var latitude: kotlin.Double
      @kotlin.jvm.JvmName("getLatitude")
        get() = _builder.latitude
      @kotlin.jvm.JvmName("setLatitude")
        set(value) {
        _builder.latitude = value
      }
    /**
     * ```
     * Latitude where session started
     * ```
     *
     * `double latitude = 9;`
     */
    public fun clearLatitude() {
      _builder.clearLatitude()
    }

    /**
     * ```
     * Longitude where session started
     * ```
     *
     * `double longitude = 10;`
     */
    public var longitude: kotlin.Double
      @kotlin.jvm.JvmName("getLongitude")
        get() = _builder.longitude
      @kotlin.jvm.JvmName("setLongitude")
        set(value) {
        _builder.longitude = value
      }
    /**
     * ```
     * Longitude where session started
     * ```
     *
     * `double longitude = 10;`
     */
    public fun clearLongitude() {
      _builder.clearLongitude()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun sdv.services.parking.GetSessionStatusResponse.copy(block: `sdv.services.parking`.GetSessionStatusResponseKt.Dsl.() -> kotlin.Unit): sdv.services.parking.GetSessionStatusResponse =
  `sdv.services.parking`.GetSessionStatusResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

