// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/parking_adaptor.proto
// Protobuf Java Version: 4.33.4

package sdv.services.parking;

@com.google.protobuf.Generated
public interface GetSessionStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdv.services.parking.GetSessionStatusRequest)
    com.google.protobuf.MessageOrBuilder {
}
