// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/parking_adaptor.proto
// Protobuf Java Version: 4.33.4

package sdv.services.parking;

@com.google.protobuf.Generated
public interface GetSessionStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdv.services.parking.GetSessionStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether there is an active session
   * </pre>
   *
   * <code>bool has_active_session = 1;</code>
   * @return The hasActiveSession.
   */
  boolean getHasActiveSession();

  /**
   * <pre>
   * Session ID (empty if no session)
   * </pre>
   *
   * <code>string session_id = 2;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * Session ID (empty if no session)
   * </pre>
   *
   * <code>string session_id = 2;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * Current session state
   * </pre>
   *
   * <code>.sdv.services.parking.SessionState state = 3;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <pre>
   * Current session state
   * </pre>
   *
   * <code>.sdv.services.parking.SessionState state = 3;</code>
   * @return The state.
   */
  sdv.services.parking.SessionState getState();

  /**
   * <pre>
   * Session start time as Unix timestamp
   * </pre>
   *
   * <code>int64 start_time_unix = 4;</code>
   * @return The startTimeUnix.
   */
  long getStartTimeUnix();

  /**
   * <pre>
   * Duration of the session in seconds
   * </pre>
   *
   * <code>int64 duration_seconds = 5;</code>
   * @return The durationSeconds.
   */
  long getDurationSeconds();

  /**
   * <pre>
   * Current cost of the session
   * </pre>
   *
   * <code>double current_cost = 6;</code>
   * @return The currentCost.
   */
  double getCurrentCost();

  /**
   * <pre>
   * Zone ID where parked
   * </pre>
   *
   * <code>string zone_id = 7;</code>
   * @return The zoneId.
   */
  java.lang.String getZoneId();
  /**
   * <pre>
   * Zone ID where parked
   * </pre>
   *
   * <code>string zone_id = 7;</code>
   * @return The bytes for zoneId.
   */
  com.google.protobuf.ByteString
      getZoneIdBytes();

  /**
   * <pre>
   * Error message if state is ERROR
   * </pre>
   *
   * <code>string error_message = 8;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <pre>
   * Error message if state is ERROR
   * </pre>
   *
   * <code>string error_message = 8;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * Latitude where session started
   * </pre>
   *
   * <code>double latitude = 9;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <pre>
   * Longitude where session started
   * </pre>
   *
   * <code>double longitude = 10;</code>
   * @return The longitude.
   */
  double getLongitude();
}
