// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/parking_adaptor.proto
// Protobuf Java Version: 4.33.4

package sdv.services.parking;

@com.google.protobuf.Generated
public final class ParkingAdaptorOuterClass extends com.google.protobuf.GeneratedFile {
  private ParkingAdaptorOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "ParkingAdaptorOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_StartSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_StartSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_StartSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_StartSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_StopSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_StopSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_StopSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_StopSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_GetSessionStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_GetSessionStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_GetSessionStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_GetSessionStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036services/parking_adaptor.proto\022\024sdv.se" +
      "rvices.parking\032\037google/protobuf/timestam" +
      "p.proto\"&\n\023StartSessionRequest\022\017\n\007zone_i" +
      "d\030\001 \001(\t\"\205\001\n\024StartSessionResponse\022\017\n\007succ" +
      "ess\030\001 \001(\010\022\025\n\rerror_message\030\002 \001(\t\022\022\n\nsess" +
      "ion_id\030\003 \001(\t\0221\n\005state\030\004 \001(\0162\".sdv.servic" +
      "es.parking.SessionState\"\024\n\022StopSessionRe" +
      "quest\"\262\001\n\023StopSessionResponse\022\017\n\007success" +
      "\030\001 \001(\010\022\025\n\rerror_message\030\002 \001(\t\022\022\n\nsession" +
      "_id\030\003 \001(\t\0221\n\005state\030\004 \001(\0162\".sdv.services." +
      "parking.SessionState\022\022\n\nfinal_cost\030\005 \001(\001" +
      "\022\030\n\020duration_seconds\030\006 \001(\003\"\031\n\027GetSession" +
      "StatusRequest\"\223\002\n\030GetSessionStatusRespon" +
      "se\022\032\n\022has_active_session\030\001 \001(\010\022\022\n\nsessio" +
      "n_id\030\002 \001(\t\0221\n\005state\030\003 \001(\0162\".sdv.services" +
      ".parking.SessionState\022\027\n\017start_time_unix" +
      "\030\004 \001(\003\022\030\n\020duration_seconds\030\005 \001(\003\022\024\n\014curr" +
      "ent_cost\030\006 \001(\001\022\017\n\007zone_id\030\007 \001(\t\022\025\n\rerror" +
      "_message\030\010 \001(\t\022\020\n\010latitude\030\t \001(\001\022\021\n\tlong" +
      "itude\030\n \001(\001*\254\001\n\014SessionState\022\026\n\022SESSION_" +
      "STATE_NONE\020\000\022\032\n\026SESSION_STATE_STARTING\020\001" +
      "\022\030\n\024SESSION_STATE_ACTIVE\020\002\022\032\n\026SESSION_ST" +
      "ATE_STOPPING\020\003\022\031\n\025SESSION_STATE_STOPPED\020" +
      "\004\022\027\n\023SESSION_STATE_ERROR\020\0052\316\002\n\016ParkingAd" +
      "aptor\022e\n\014StartSession\022).sdv.services.par" +
      "king.StartSessionRequest\032*.sdv.services." +
      "parking.StartSessionResponse\022b\n\013StopSess" +
      "ion\022(.sdv.services.parking.StopSessionRe" +
      "quest\032).sdv.services.parking.StopSession" +
      "Response\022q\n\020GetSessionStatus\022-.sdv.servi" +
      "ces.parking.GetSessionStatusRequest\032..sd" +
      "v.services.parking.GetSessionStatusRespo" +
      "nseBR\n\024sdv.services.parkingP\001Z8github.co" +
      "m/sdv-parking-demo/backend/gen/services/" +
      "parkingb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_sdv_services_parking_StartSessionRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_sdv_services_parking_StartSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_StartSessionRequest_descriptor,
        new java.lang.String[] { "ZoneId", });
    internal_static_sdv_services_parking_StartSessionResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_sdv_services_parking_StartSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_StartSessionResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorMessage", "SessionId", "State", });
    internal_static_sdv_services_parking_StopSessionRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_sdv_services_parking_StopSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_StopSessionRequest_descriptor,
        new java.lang.String[] { });
    internal_static_sdv_services_parking_StopSessionResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_sdv_services_parking_StopSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_StopSessionResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorMessage", "SessionId", "State", "FinalCost", "DurationSeconds", });
    internal_static_sdv_services_parking_GetSessionStatusRequest_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_sdv_services_parking_GetSessionStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_GetSessionStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_sdv_services_parking_GetSessionStatusResponse_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_sdv_services_parking_GetSessionStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_GetSessionStatusResponse_descriptor,
        new java.lang.String[] { "HasActiveSession", "SessionId", "State", "StartTimeUnix", "DurationSeconds", "CurrentCost", "ZoneId", "ErrorMessage", "Latitude", "Longitude", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
