// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/parking_adaptor.proto
// Protobuf Java Version: 4.33.4

package sdv.services.parking;

@com.google.protobuf.Generated
public final class ParkingAdaptorOuterClass extends com.google.protobuf.GeneratedFile {
  private ParkingAdaptorOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "ParkingAdaptorOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_StartSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_StartSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_StartSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_StartSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_StopSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_StopSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_StopSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_StopSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_GetSessionStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_GetSessionStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_parking_GetSessionStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_parking_GetSessionStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036services/parking_adaptor.proto\022\024sdv.se" +
      "rvices.parking\032\037google/protobuf/timestam" +
      "p.proto\"_\n\023StartSessionRequest\022\022\n\nvehicl" +
      "e_id\030\001 \001(\t\022\017\n\007zone_id\030\002 \001(\t\022\020\n\010latitude\030" +
      "\003 \001(\001\022\021\n\tlongitude\030\004 \001(\001\"\220\001\n\024StartSessio" +
      "nResponse\022\022\n\nsession_id\030\001 \001(\t\022\017\n\007success" +
      "\030\002 \001(\010\022\025\n\rerror_message\030\003 \001(\t\022\025\n\roperato" +
      "r_name\030\004 \001(\t\022\023\n\013hourly_rate\030\005 \001(\001\022\020\n\010cur" +
      "rency\030\006 \001(\t\"(\n\022StopSessionRequest\022\022\n\nses" +
      "sion_id\030\001 \001(\t\"\177\n\023StopSessionResponse\022\017\n\007" +
      "success\030\001 \001(\010\022\025\n\rerror_message\030\002 \001(\t\022\024\n\014" +
      "total_amount\030\003 \001(\001\022\020\n\010currency\030\004 \001(\t\022\030\n\020" +
      "duration_seconds\030\005 \001(\003\"-\n\027GetSessionStat" +
      "usRequest\022\022\n\nsession_id\030\001 \001(\t\"\230\001\n\030GetSes" +
      "sionStatusResponse\022\022\n\nsession_id\030\001 \001(\t\022\016" +
      "\n\006active\030\002 \001(\010\022.\n\nstart_time\030\003 \001(\0132\032.goo" +
      "gle.protobuf.Timestamp\022\026\n\016current_amount" +
      "\030\004 \001(\001\022\020\n\010currency\030\005 \001(\t2\316\002\n\016ParkingAdap" +
      "tor\022e\n\014StartSession\022).sdv.services.parki" +
      "ng.StartSessionRequest\032*.sdv.services.pa" +
      "rking.StartSessionResponse\022b\n\013StopSessio" +
      "n\022(.sdv.services.parking.StopSessionRequ" +
      "est\032).sdv.services.parking.StopSessionRe" +
      "sponse\022q\n\020GetSessionStatus\022-.sdv.service" +
      "s.parking.GetSessionStatusRequest\032..sdv." +
      "services.parking.GetSessionStatusRespons" +
      "eBR\n\024sdv.services.parkingP\001Z8github.com/" +
      "sdv-parking-demo/backend/gen/services/pa" +
      "rkingb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_sdv_services_parking_StartSessionRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_sdv_services_parking_StartSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_StartSessionRequest_descriptor,
        new java.lang.String[] { "VehicleId", "ZoneId", "Latitude", "Longitude", });
    internal_static_sdv_services_parking_StartSessionResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_sdv_services_parking_StartSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_StartSessionResponse_descriptor,
        new java.lang.String[] { "SessionId", "Success", "ErrorMessage", "OperatorName", "HourlyRate", "Currency", });
    internal_static_sdv_services_parking_StopSessionRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_sdv_services_parking_StopSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_StopSessionRequest_descriptor,
        new java.lang.String[] { "SessionId", });
    internal_static_sdv_services_parking_StopSessionResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_sdv_services_parking_StopSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_StopSessionResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorMessage", "TotalAmount", "Currency", "DurationSeconds", });
    internal_static_sdv_services_parking_GetSessionStatusRequest_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_sdv_services_parking_GetSessionStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_GetSessionStatusRequest_descriptor,
        new java.lang.String[] { "SessionId", });
    internal_static_sdv_services_parking_GetSessionStatusResponse_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_sdv_services_parking_GetSessionStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_parking_GetSessionStatusResponse_descriptor,
        new java.lang.String[] { "SessionId", "Active", "StartTime", "CurrentAmount", "Currency", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
