// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/parking_adaptor.proto
// Protobuf Java Version: 4.33.4

package sdv.services.parking;

@com.google.protobuf.Generated
public interface StartSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdv.services.parking.StartSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string vehicle_id = 1;</code>
   * @return The vehicleId.
   */
  java.lang.String getVehicleId();
  /**
   * <code>string vehicle_id = 1;</code>
   * @return The bytes for vehicleId.
   */
  com.google.protobuf.ByteString
      getVehicleIdBytes();

  /**
   * <code>string zone_id = 2;</code>
   * @return The zoneId.
   */
  java.lang.String getZoneId();
  /**
   * <code>string zone_id = 2;</code>
   * @return The bytes for zoneId.
   */
  com.google.protobuf.ByteString
      getZoneIdBytes();

  /**
   * <code>double latitude = 3;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <code>double longitude = 4;</code>
   * @return The longitude.
   */
  double getLongitude();
}
