// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/parking_adaptor.proto
// Protobuf Java Version: 4.33.4

package sdv.services.parking;

/**
 * <pre>
 * Request to start a parking session.
 * </pre>
 *
 * Protobuf type {@code sdv.services.parking.StartSessionRequest}
 */
@com.google.protobuf.Generated
public final class StartSessionRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sdv.services.parking.StartSessionRequest)
    StartSessionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "StartSessionRequest");
  }
  // Use StartSessionRequest.newBuilder() to construct.
  private StartSessionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StartSessionRequest() {
    zoneId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sdv.services.parking.ParkingAdaptorOuterClass.internal_static_sdv_services_parking_StartSessionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sdv.services.parking.ParkingAdaptorOuterClass.internal_static_sdv_services_parking_StartSessionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sdv.services.parking.StartSessionRequest.class, sdv.services.parking.StartSessionRequest.Builder.class);
  }

  public static final int ZONE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object zoneId_ = "";
  /**
   * <pre>
   * Zone_ID provided by PARKING_APP (obtained from PARKING_FEE_SERVICE based on location)
   * </pre>
   *
   * <code>string zone_id = 1;</code>
   * @return The zoneId.
   */
  @java.lang.Override
  public java.lang.String getZoneId() {
    java.lang.Object ref = zoneId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      zoneId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Zone_ID provided by PARKING_APP (obtained from PARKING_FEE_SERVICE based on location)
   * </pre>
   *
   * <code>string zone_id = 1;</code>
   * @return The bytes for zoneId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getZoneIdBytes() {
    java.lang.Object ref = zoneId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      zoneId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(zoneId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, zoneId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(zoneId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, zoneId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sdv.services.parking.StartSessionRequest)) {
      return super.equals(obj);
    }
    sdv.services.parking.StartSessionRequest other = (sdv.services.parking.StartSessionRequest) obj;

    if (!getZoneId()
        .equals(other.getZoneId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ZONE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getZoneId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sdv.services.parking.StartSessionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.parking.StartSessionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.parking.StartSessionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.parking.StartSessionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.parking.StartSessionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.parking.StartSessionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.parking.StartSessionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sdv.services.parking.StartSessionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sdv.services.parking.StartSessionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sdv.services.parking.StartSessionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdv.services.parking.StartSessionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sdv.services.parking.StartSessionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sdv.services.parking.StartSessionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request to start a parking session.
   * </pre>
   *
   * Protobuf type {@code sdv.services.parking.StartSessionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sdv.services.parking.StartSessionRequest)
      sdv.services.parking.StartSessionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sdv.services.parking.ParkingAdaptorOuterClass.internal_static_sdv_services_parking_StartSessionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sdv.services.parking.ParkingAdaptorOuterClass.internal_static_sdv_services_parking_StartSessionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sdv.services.parking.StartSessionRequest.class, sdv.services.parking.StartSessionRequest.Builder.class);
    }

    // Construct using sdv.services.parking.StartSessionRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      zoneId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sdv.services.parking.ParkingAdaptorOuterClass.internal_static_sdv_services_parking_StartSessionRequest_descriptor;
    }

    @java.lang.Override
    public sdv.services.parking.StartSessionRequest getDefaultInstanceForType() {
      return sdv.services.parking.StartSessionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public sdv.services.parking.StartSessionRequest build() {
      sdv.services.parking.StartSessionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sdv.services.parking.StartSessionRequest buildPartial() {
      sdv.services.parking.StartSessionRequest result = new sdv.services.parking.StartSessionRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(sdv.services.parking.StartSessionRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.zoneId_ = zoneId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sdv.services.parking.StartSessionRequest) {
        return mergeFrom((sdv.services.parking.StartSessionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sdv.services.parking.StartSessionRequest other) {
      if (other == sdv.services.parking.StartSessionRequest.getDefaultInstance()) return this;
      if (!other.getZoneId().isEmpty()) {
        zoneId_ = other.zoneId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              zoneId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object zoneId_ = "";
    /**
     * <pre>
     * Zone_ID provided by PARKING_APP (obtained from PARKING_FEE_SERVICE based on location)
     * </pre>
     *
     * <code>string zone_id = 1;</code>
     * @return The zoneId.
     */
    public java.lang.String getZoneId() {
      java.lang.Object ref = zoneId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zoneId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Zone_ID provided by PARKING_APP (obtained from PARKING_FEE_SERVICE based on location)
     * </pre>
     *
     * <code>string zone_id = 1;</code>
     * @return The bytes for zoneId.
     */
    public com.google.protobuf.ByteString
        getZoneIdBytes() {
      java.lang.Object ref = zoneId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zoneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Zone_ID provided by PARKING_APP (obtained from PARKING_FEE_SERVICE based on location)
     * </pre>
     *
     * <code>string zone_id = 1;</code>
     * @param value The zoneId to set.
     * @return This builder for chaining.
     */
    public Builder setZoneId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      zoneId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Zone_ID provided by PARKING_APP (obtained from PARKING_FEE_SERVICE based on location)
     * </pre>
     *
     * <code>string zone_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearZoneId() {
      zoneId_ = getDefaultInstance().getZoneId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Zone_ID provided by PARKING_APP (obtained from PARKING_FEE_SERVICE based on location)
     * </pre>
     *
     * <code>string zone_id = 1;</code>
     * @param value The bytes for zoneId to set.
     * @return This builder for chaining.
     */
    public Builder setZoneIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      zoneId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sdv.services.parking.StartSessionRequest)
  }

  // @@protoc_insertion_point(class_scope:sdv.services.parking.StartSessionRequest)
  private static final sdv.services.parking.StartSessionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sdv.services.parking.StartSessionRequest();
  }

  public static sdv.services.parking.StartSessionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StartSessionRequest>
      PARSER = new com.google.protobuf.AbstractParser<StartSessionRequest>() {
    @java.lang.Override
    public StartSessionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StartSessionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StartSessionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sdv.services.parking.StartSessionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

