// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/parking_adaptor.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package sdv.services.parking;

@kotlin.jvm.JvmName("-initializestopSessionResponse")
public inline fun stopSessionResponse(block: sdv.services.parking.StopSessionResponseKt.Dsl.() -> kotlin.Unit): sdv.services.parking.StopSessionResponse =
  sdv.services.parking.StopSessionResponseKt.Dsl._create(sdv.services.parking.StopSessionResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * Response from stopping a parking session.
 * ```
 *
 * Protobuf type `sdv.services.parking.StopSessionResponse`
 */
public object StopSessionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: sdv.services.parking.StopSessionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: sdv.services.parking.StopSessionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): sdv.services.parking.StopSessionResponse = _builder.build()

    /**
     * ```
     * Whether the operation succeeded
     * ```
     *
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * ```
     * Whether the operation succeeded
     * ```
     *
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * ```
     * Error message if failed
     * ```
     *
     * `string error_message = 2;`
     */
    public var errorMessage: kotlin.String
      @kotlin.jvm.JvmName("getErrorMessage")
        get() = _builder.errorMessage
      @kotlin.jvm.JvmName("setErrorMessage")
        set(value) {
        _builder.errorMessage = value
      }
    /**
     * ```
     * Error message if failed
     * ```
     *
     * `string error_message = 2;`
     */
    public fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }

    /**
     * ```
     * Session ID that was stopped
     * ```
     *
     * `string session_id = 3;`
     */
    public var sessionId: kotlin.String
      @kotlin.jvm.JvmName("getSessionId")
        get() = _builder.sessionId
      @kotlin.jvm.JvmName("setSessionId")
        set(value) {
        _builder.sessionId = value
      }
    /**
     * ```
     * Session ID that was stopped
     * ```
     *
     * `string session_id = 3;`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * ```
     * Current session state
     * ```
     *
     * `.sdv.services.parking.SessionState state = 4;`
     */
    public var state: sdv.services.parking.SessionState
      @kotlin.jvm.JvmName("getState")
        get() = _builder.state
      @kotlin.jvm.JvmName("setState")
        set(value) {
        _builder.state = value
      }
    public var stateValue: kotlin.Int
      @kotlin.jvm.JvmName("getStateValue")
        get() = _builder.stateValue
      @kotlin.jvm.JvmName("setStateValue")
        set(value) {
        _builder.stateValue = value
      }
    /**
     * ```
     * Current session state
     * ```
     *
     * `.sdv.services.parking.SessionState state = 4;`
     */
    public fun clearState() {
      _builder.clearState()
    }

    /**
     * ```
     * Final cost of the session
     * ```
     *
     * `double final_cost = 5;`
     */
    public var finalCost: kotlin.Double
      @kotlin.jvm.JvmName("getFinalCost")
        get() = _builder.finalCost
      @kotlin.jvm.JvmName("setFinalCost")
        set(value) {
        _builder.finalCost = value
      }
    /**
     * ```
     * Final cost of the session
     * ```
     *
     * `double final_cost = 5;`
     */
    public fun clearFinalCost() {
      _builder.clearFinalCost()
    }

    /**
     * ```
     * Duration of the session in seconds
     * ```
     *
     * `int64 duration_seconds = 6;`
     */
    public var durationSeconds: kotlin.Long
      @kotlin.jvm.JvmName("getDurationSeconds")
        get() = _builder.durationSeconds
      @kotlin.jvm.JvmName("setDurationSeconds")
        set(value) {
        _builder.durationSeconds = value
      }
    /**
     * ```
     * Duration of the session in seconds
     * ```
     *
     * `int64 duration_seconds = 6;`
     */
    public fun clearDurationSeconds() {
      _builder.clearDurationSeconds()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun sdv.services.parking.StopSessionResponse.copy(block: `sdv.services.parking`.StopSessionResponseKt.Dsl.() -> kotlin.Unit): sdv.services.parking.StopSessionResponse =
  `sdv.services.parking`.StopSessionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

