// Minimal kuksa.val.v1 proto vendored for mock-sensors.
// Only the Set RPC and the types it requires are included.
// Source: https://github.com/eclipse/kuksa.val (simplified subset).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: val.proto

package kuksa_val_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Fields that can be updated in an EntryUpdate.
type Field int32

const (
	Field_FIELD_UNSPECIFIED Field = 0
	Field_FIELD_PATH        Field = 1
	Field_FIELD_VALUE       Field = 2
)

// Enum value maps for Field.
var (
	Field_name = map[int32]string{
		0: "FIELD_UNSPECIFIED",
		1: "FIELD_PATH",
		2: "FIELD_VALUE",
	}
	Field_value = map[string]int32{
		"FIELD_UNSPECIFIED": 0,
		"FIELD_PATH":        1,
		"FIELD_VALUE":       2,
	}
)

func (x Field) Enum() *Field {
	p := new(Field)
	*p = x
	return p
}

func (x Field) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field) Descriptor() protoreflect.EnumDescriptor {
	return file_val_proto_enumTypes[0].Descriptor()
}

func (Field) Type() protoreflect.EnumType {
	return &file_val_proto_enumTypes[0]
}

func (x Field) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field.Descriptor instead.
func (Field) EnumDescriptor() ([]byte, []int) {
	return file_val_proto_rawDescGZIP(), []int{0}
}

// A typed sensor or actuator value.
type Datapoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Datapoint_String_
	//	*Datapoint_Bool
	//	*Datapoint_Int32
	//	*Datapoint_Int64
	//	*Datapoint_Uint32
	//	*Datapoint_Uint64
	//	*Datapoint_Float
	//	*Datapoint_Double
	Value         isDatapoint_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Datapoint) Reset() {
	*x = Datapoint{}
	mi := &file_val_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Datapoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Datapoint) ProtoMessage() {}

func (x *Datapoint) ProtoReflect() protoreflect.Message {
	mi := &file_val_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Datapoint.ProtoReflect.Descriptor instead.
func (*Datapoint) Descriptor() ([]byte, []int) {
	return file_val_proto_rawDescGZIP(), []int{0}
}

func (x *Datapoint) GetValue() isDatapoint_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Datapoint) GetString_() string {
	if x != nil {
		if x, ok := x.Value.(*Datapoint_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *Datapoint) GetBool() bool {
	if x != nil {
		if x, ok := x.Value.(*Datapoint_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *Datapoint) GetInt32() int32 {
	if x != nil {
		if x, ok := x.Value.(*Datapoint_Int32); ok {
			return x.Int32
		}
	}
	return 0
}

func (x *Datapoint) GetInt64() int64 {
	if x != nil {
		if x, ok := x.Value.(*Datapoint_Int64); ok {
			return x.Int64
		}
	}
	return 0
}

func (x *Datapoint) GetUint32() uint32 {
	if x != nil {
		if x, ok := x.Value.(*Datapoint_Uint32); ok {
			return x.Uint32
		}
	}
	return 0
}

func (x *Datapoint) GetUint64() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Datapoint_Uint64); ok {
			return x.Uint64
		}
	}
	return 0
}

func (x *Datapoint) GetFloat() float32 {
	if x != nil {
		if x, ok := x.Value.(*Datapoint_Float); ok {
			return x.Float
		}
	}
	return 0
}

func (x *Datapoint) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Value.(*Datapoint_Double); ok {
			return x.Double
		}
	}
	return 0
}

type isDatapoint_Value interface {
	isDatapoint_Value()
}

type Datapoint_String_ struct {
	String_ string `protobuf:"bytes,11,opt,name=string,proto3,oneof"`
}

type Datapoint_Bool struct {
	Bool bool `protobuf:"varint,12,opt,name=bool,proto3,oneof"`
}

type Datapoint_Int32 struct {
	Int32 int32 `protobuf:"varint,13,opt,name=int32,proto3,oneof"`
}

type Datapoint_Int64 struct {
	Int64 int64 `protobuf:"varint,14,opt,name=int64,proto3,oneof"`
}

type Datapoint_Uint32 struct {
	Uint32 uint32 `protobuf:"varint,15,opt,name=uint32,proto3,oneof"`
}

type Datapoint_Uint64 struct {
	Uint64 uint64 `protobuf:"varint,16,opt,name=uint64,proto3,oneof"`
}

type Datapoint_Float struct {
	Float float32 `protobuf:"fixed32,17,opt,name=float,proto3,oneof"`
}

type Datapoint_Double struct {
	Double float64 `protobuf:"fixed64,18,opt,name=double,proto3,oneof"`
}

func (*Datapoint_String_) isDatapoint_Value() {}

func (*Datapoint_Bool) isDatapoint_Value() {}

func (*Datapoint_Int32) isDatapoint_Value() {}

func (*Datapoint_Int64) isDatapoint_Value() {}

func (*Datapoint_Uint32) isDatapoint_Value() {}

func (*Datapoint_Uint64) isDatapoint_Value() {}

func (*Datapoint_Float) isDatapoint_Value() {}

func (*Datapoint_Double) isDatapoint_Value() {}

// A VSS data-tree entry: path + current value.
type DataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value         *Datapoint             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataEntry) Reset() {
	*x = DataEntry{}
	mi := &file_val_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEntry) ProtoMessage() {}

func (x *DataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_val_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEntry.ProtoReflect.Descriptor instead.
func (*DataEntry) Descriptor() ([]byte, []int) {
	return file_val_proto_rawDescGZIP(), []int{1}
}

func (x *DataEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DataEntry) GetValue() *Datapoint {
	if x != nil {
		return x.Value
	}
	return nil
}

// Pairs a DataEntry with the fields that should be written.
type EntryUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *DataEntry             `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Fields        []Field                `protobuf:"varint,2,rep,packed,name=fields,proto3,enum=kuksa.val.v1.Field" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryUpdate) Reset() {
	*x = EntryUpdate{}
	mi := &file_val_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryUpdate) ProtoMessage() {}

func (x *EntryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_val_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryUpdate.ProtoReflect.Descriptor instead.
func (*EntryUpdate) Descriptor() ([]byte, []int) {
	return file_val_proto_rawDescGZIP(), []int{2}
}

func (x *EntryUpdate) GetEntry() *DataEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *EntryUpdate) GetFields() []Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Describes an error returned by the databroker.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_val_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_val_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_val_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Per-entry error detail.
type EntryError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryError) Reset() {
	*x = EntryError{}
	mi := &file_val_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryError) ProtoMessage() {}

func (x *EntryError) ProtoReflect() protoreflect.Message {
	mi := &file_val_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryError.ProtoReflect.Descriptor instead.
func (*EntryError) Descriptor() ([]byte, []int) {
	return file_val_proto_rawDescGZIP(), []int{4}
}

func (x *EntryError) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EntryError) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Request for the Set RPC.
type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*EntryUpdate         `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_val_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_val_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_val_proto_rawDescGZIP(), []int{5}
}

func (x *SetRequest) GetUpdates() []*EntryUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

// Response from the Set RPC.
type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Errors        []*EntryError          `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_val_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_val_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_val_proto_rawDescGZIP(), []int{6}
}

func (x *SetResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SetResponse) GetErrors() []*EntryError {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_val_proto protoreflect.FileDescriptor

const file_val_proto_rawDesc = "" +
	"\n" +
	"\tval.proto\x12\fkuksa.val.v1\"\xda\x01\n" +
	"\tDatapoint\x12\x18\n" +
	"\x06string\x18\v \x01(\tH\x00R\x06string\x12\x14\n" +
	"\x04bool\x18\f \x01(\bH\x00R\x04bool\x12\x16\n" +
	"\x05int32\x18\r \x01(\x05H\x00R\x05int32\x12\x16\n" +
	"\x05int64\x18\x0e \x01(\x03H\x00R\x05int64\x12\x18\n" +
	"\x06uint32\x18\x0f \x01(\rH\x00R\x06uint32\x12\x18\n" +
	"\x06uint64\x18\x10 \x01(\x04H\x00R\x06uint64\x12\x16\n" +
	"\x05float\x18\x11 \x01(\x02H\x00R\x05float\x12\x18\n" +
	"\x06double\x18\x12 \x01(\x01H\x00R\x06doubleB\a\n" +
	"\x05value\"N\n" +
	"\tDataEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.kuksa.val.v1.DatapointR\x05value\"i\n" +
	"\vEntryUpdate\x12-\n" +
	"\x05entry\x18\x01 \x01(\v2\x17.kuksa.val.v1.DataEntryR\x05entry\x12+\n" +
	"\x06fields\x18\x02 \x03(\x0e2\x13.kuksa.val.v1.FieldR\x06fields\"M\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"K\n" +
	"\n" +
	"EntryError\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x13.kuksa.val.v1.ErrorR\x05error\"A\n" +
	"\n" +
	"SetRequest\x123\n" +
	"\aupdates\x18\x01 \x03(\v2\x19.kuksa.val.v1.EntryUpdateR\aupdates\"j\n" +
	"\vSetResponse\x12)\n" +
	"\x05error\x18\x01 \x01(\v2\x13.kuksa.val.v1.ErrorR\x05error\x120\n" +
	"\x06errors\x18\x02 \x03(\v2\x18.kuksa.val.v1.EntryErrorR\x06errors*?\n" +
	"\x05Field\x12\x15\n" +
	"\x11FIELD_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"FIELD_PATH\x10\x01\x12\x0f\n" +
	"\vFIELD_VALUE\x10\x022H\n" +
	"\n" +
	"VALService\x12:\n" +
	"\x03Set\x12\x18.kuksa.val.v1.SetRequest\x1a\x19.kuksa.val.v1.SetResponseb\x06proto3"

var (
	file_val_proto_rawDescOnce sync.Once
	file_val_proto_rawDescData []byte
)

func file_val_proto_rawDescGZIP() []byte {
	file_val_proto_rawDescOnce.Do(func() {
		file_val_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_val_proto_rawDesc), len(file_val_proto_rawDesc)))
	})
	return file_val_proto_rawDescData
}

var file_val_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_val_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_val_proto_goTypes = []any{
	(Field)(0),          // 0: kuksa.val.v1.Field
	(*Datapoint)(nil),   // 1: kuksa.val.v1.Datapoint
	(*DataEntry)(nil),   // 2: kuksa.val.v1.DataEntry
	(*EntryUpdate)(nil), // 3: kuksa.val.v1.EntryUpdate
	(*Error)(nil),       // 4: kuksa.val.v1.Error
	(*EntryError)(nil),  // 5: kuksa.val.v1.EntryError
	(*SetRequest)(nil),  // 6: kuksa.val.v1.SetRequest
	(*SetResponse)(nil), // 7: kuksa.val.v1.SetResponse
}
var file_val_proto_depIdxs = []int32{
	1, // 0: kuksa.val.v1.DataEntry.value:type_name -> kuksa.val.v1.Datapoint
	2, // 1: kuksa.val.v1.EntryUpdate.entry:type_name -> kuksa.val.v1.DataEntry
	0, // 2: kuksa.val.v1.EntryUpdate.fields:type_name -> kuksa.val.v1.Field
	4, // 3: kuksa.val.v1.EntryError.error:type_name -> kuksa.val.v1.Error
	3, // 4: kuksa.val.v1.SetRequest.updates:type_name -> kuksa.val.v1.EntryUpdate
	4, // 5: kuksa.val.v1.SetResponse.error:type_name -> kuksa.val.v1.Error
	5, // 6: kuksa.val.v1.SetResponse.errors:type_name -> kuksa.val.v1.EntryError
	6, // 7: kuksa.val.v1.VALService.Set:input_type -> kuksa.val.v1.SetRequest
	7, // 8: kuksa.val.v1.VALService.Set:output_type -> kuksa.val.v1.SetResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_val_proto_init() }
func file_val_proto_init() {
	if File_val_proto != nil {
		return
	}
	file_val_proto_msgTypes[0].OneofWrappers = []any{
		(*Datapoint_String_)(nil),
		(*Datapoint_Bool)(nil),
		(*Datapoint_Int32)(nil),
		(*Datapoint_Int64)(nil),
		(*Datapoint_Uint32)(nil),
		(*Datapoint_Uint64)(nil),
		(*Datapoint_Float)(nil),
		(*Datapoint_Double)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_val_proto_rawDesc), len(file_val_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_val_proto_goTypes,
		DependencyIndexes: file_val_proto_depIdxs,
		EnumInfos:         file_val_proto_enumTypes,
		MessageInfos:      file_val_proto_msgTypes,
	}.Build()
	File_val_proto = out.File
	file_val_proto_goTypes = nil
	file_val_proto_depIdxs = nil
}
