// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: parking_adaptor.proto

package adaptor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RateInfo describes the pricing structure for a parking session.
type RateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RateType      string                 `protobuf:"bytes,1,opt,name=rate_type,json=rateType,proto3" json:"rate_type,omitempty"` // "per_hour" or "flat_fee"
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateInfo) Reset() {
	*x = RateInfo{}
	mi := &file_parking_adaptor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateInfo) ProtoMessage() {}

func (x *RateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_parking_adaptor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateInfo.ProtoReflect.Descriptor instead.
func (*RateInfo) Descriptor() ([]byte, []int) {
	return file_parking_adaptor_proto_rawDescGZIP(), []int{0}
}

func (x *RateInfo) GetRateType() string {
	if x != nil {
		return x.RateType
	}
	return ""
}

func (x *RateInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RateInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// StartSessionRequest initiates a parking session for the given zone.
type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_parking_adaptor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_adaptor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_parking_adaptor_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

// StartSessionResponse is returned by StartSession on success.
type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Rate          *RateInfo              `protobuf:"bytes,3,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_parking_adaptor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_adaptor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_parking_adaptor_proto_rawDescGZIP(), []int{2}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartSessionResponse) GetRate() *RateInfo {
	if x != nil {
		return x.Rate
	}
	return nil
}

// StopSessionRequest terminates the active parking session.
type StopSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionRequest) Reset() {
	*x = StopSessionRequest{}
	mi := &file_parking_adaptor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionRequest) ProtoMessage() {}

func (x *StopSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_adaptor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionRequest.ProtoReflect.Descriptor instead.
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return file_parking_adaptor_proto_rawDescGZIP(), []int{3}
}

// StopSessionResponse is returned by StopSession on success.
type StopSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	DurationSeconds uint64                 `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	TotalAmount     float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StopSessionResponse) Reset() {
	*x = StopSessionResponse{}
	mi := &file_parking_adaptor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionResponse) ProtoMessage() {}

func (x *StopSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_adaptor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionResponse.ProtoReflect.Descriptor instead.
func (*StopSessionResponse) Descriptor() ([]byte, []int) {
	return file_parking_adaptor_proto_rawDescGZIP(), []int{4}
}

func (x *StopSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StopSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StopSessionResponse) GetDurationSeconds() uint64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *StopSessionResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *StopSessionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// GetStatusRequest requests the current session status.
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_parking_adaptor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_adaptor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_parking_adaptor_proto_rawDescGZIP(), []int{5}
}

// GetStatusResponse describes the current session state.
type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ZoneId        string                 `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Rate          *RateInfo              `protobuf:"bytes,5,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_parking_adaptor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_adaptor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_parking_adaptor_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GetStatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetStatusResponse) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *GetStatusResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetStatusResponse) GetRate() *RateInfo {
	if x != nil {
		return x.Rate
	}
	return nil
}

// GetRateRequest requests the cached parking rate.
type GetRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateRequest) Reset() {
	*x = GetRateRequest{}
	mi := &file_parking_adaptor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateRequest) ProtoMessage() {}

func (x *GetRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_adaptor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateRequest.ProtoReflect.Descriptor instead.
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return file_parking_adaptor_proto_rawDescGZIP(), []int{7}
}

// GetRateResponse describes the rate for the current session.
type GetRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RateType      string                 `protobuf:"bytes,1,opt,name=rate_type,json=rateType,proto3" json:"rate_type,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateResponse) Reset() {
	*x = GetRateResponse{}
	mi := &file_parking_adaptor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateResponse) ProtoMessage() {}

func (x *GetRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_adaptor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateResponse.ProtoReflect.Descriptor instead.
func (*GetRateResponse) Descriptor() ([]byte, []int) {
	return file_parking_adaptor_proto_rawDescGZIP(), []int{8}
}

func (x *GetRateResponse) GetRateType() string {
	if x != nil {
		return x.RateType
	}
	return ""
}

func (x *GetRateResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetRateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_parking_adaptor_proto protoreflect.FileDescriptor

const file_parking_adaptor_proto_rawDesc = "" +
	"\n" +
	"\x15parking_adaptor.proto\x12\x0fparking.adaptor\"[\n" +
	"\bRateInfo\x12\x1b\n" +
	"\trate_type\x18\x01 \x01(\tR\brateType\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\".\n" +
	"\x13StartSessionRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\"|\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\x04rate\x18\x03 \x01(\v2\x19.parking.adaptor.RateInfoR\x04rate\"\x14\n" +
	"\x12StopSessionRequest\"\xb6\x01\n" +
	"\x13StopSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x04R\x0fdurationSeconds\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\x12\n" +
	"\x10GetStatusRequest\"\xb1\x01\n" +
	"\x11GetStatusResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\tR\x06zoneId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12-\n" +
	"\x04rate\x18\x05 \x01(\v2\x19.parking.adaptor.RateInfoR\x04rate\"\x10\n" +
	"\x0eGetRateRequest\"b\n" +
	"\x0fGetRateResponse\x12\x1b\n" +
	"\trate_type\x18\x01 \x01(\tR\brateType\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency2\xe9\x02\n" +
	"\x0eParkingAdaptor\x12[\n" +
	"\fStartSession\x12$.parking.adaptor.StartSessionRequest\x1a%.parking.adaptor.StartSessionResponse\x12X\n" +
	"\vStopSession\x12#.parking.adaptor.StopSessionRequest\x1a$.parking.adaptor.StopSessionResponse\x12R\n" +
	"\tGetStatus\x12!.parking.adaptor.GetStatusRequest\x1a\".parking.adaptor.GetStatusResponse\x12L\n" +
	"\aGetRate\x12\x1f.parking.adaptor.GetRateRequest\x1a .parking.adaptor.GetRateResponseB:Z8github.com/rhadp/parking-fee-service/gen/parking/adaptorb\x06proto3"

var (
	file_parking_adaptor_proto_rawDescOnce sync.Once
	file_parking_adaptor_proto_rawDescData []byte
)

func file_parking_adaptor_proto_rawDescGZIP() []byte {
	file_parking_adaptor_proto_rawDescOnce.Do(func() {
		file_parking_adaptor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parking_adaptor_proto_rawDesc), len(file_parking_adaptor_proto_rawDesc)))
	})
	return file_parking_adaptor_proto_rawDescData
}

var file_parking_adaptor_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_parking_adaptor_proto_goTypes = []any{
	(*RateInfo)(nil),             // 0: parking.adaptor.RateInfo
	(*StartSessionRequest)(nil),  // 1: parking.adaptor.StartSessionRequest
	(*StartSessionResponse)(nil), // 2: parking.adaptor.StartSessionResponse
	(*StopSessionRequest)(nil),   // 3: parking.adaptor.StopSessionRequest
	(*StopSessionResponse)(nil),  // 4: parking.adaptor.StopSessionResponse
	(*GetStatusRequest)(nil),     // 5: parking.adaptor.GetStatusRequest
	(*GetStatusResponse)(nil),    // 6: parking.adaptor.GetStatusResponse
	(*GetRateRequest)(nil),       // 7: parking.adaptor.GetRateRequest
	(*GetRateResponse)(nil),      // 8: parking.adaptor.GetRateResponse
}
var file_parking_adaptor_proto_depIdxs = []int32{
	0, // 0: parking.adaptor.StartSessionResponse.rate:type_name -> parking.adaptor.RateInfo
	0, // 1: parking.adaptor.GetStatusResponse.rate:type_name -> parking.adaptor.RateInfo
	1, // 2: parking.adaptor.ParkingAdaptor.StartSession:input_type -> parking.adaptor.StartSessionRequest
	3, // 3: parking.adaptor.ParkingAdaptor.StopSession:input_type -> parking.adaptor.StopSessionRequest
	5, // 4: parking.adaptor.ParkingAdaptor.GetStatus:input_type -> parking.adaptor.GetStatusRequest
	7, // 5: parking.adaptor.ParkingAdaptor.GetRate:input_type -> parking.adaptor.GetRateRequest
	2, // 6: parking.adaptor.ParkingAdaptor.StartSession:output_type -> parking.adaptor.StartSessionResponse
	4, // 7: parking.adaptor.ParkingAdaptor.StopSession:output_type -> parking.adaptor.StopSessionResponse
	6, // 8: parking.adaptor.ParkingAdaptor.GetStatus:output_type -> parking.adaptor.GetStatusResponse
	8, // 9: parking.adaptor.ParkingAdaptor.GetRate:output_type -> parking.adaptor.GetRateResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_parking_adaptor_proto_init() }
func file_parking_adaptor_proto_init() {
	if File_parking_adaptor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parking_adaptor_proto_rawDesc), len(file_parking_adaptor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parking_adaptor_proto_goTypes,
		DependencyIndexes: file_parking_adaptor_proto_depIdxs,
		MessageInfos:      file_parking_adaptor_proto_msgTypes,
	}.Build()
	File_parking_adaptor_proto = out.File
	file_parking_adaptor_proto_goTypes = nil
	file_parking_adaptor_proto_depIdxs = nil
}
