// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/update_service.proto
// Protobuf Java Version: 4.33.4

package sdv.services.update;

/**
 * <pre>
 * AdapterStateEvent represents a state change event for an adapter
 * </pre>
 *
 * Protobuf type {@code sdv.services.update.AdapterStateEvent}
 */
@com.google.protobuf.Generated
public final class AdapterStateEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sdv.services.update.AdapterStateEvent)
    AdapterStateEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "AdapterStateEvent");
  }
  // Use AdapterStateEvent.newBuilder() to construct.
  private AdapterStateEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AdapterStateEvent() {
    adapterId_ = "";
    oldState_ = 0;
    newState_ = 0;
    errorMessage_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sdv.services.update.UpdateServiceOuterClass.internal_static_sdv_services_update_AdapterStateEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sdv.services.update.UpdateServiceOuterClass.internal_static_sdv_services_update_AdapterStateEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sdv.services.update.AdapterStateEvent.class, sdv.services.update.AdapterStateEvent.Builder.class);
  }

  public static final int ADAPTER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object adapterId_ = "";
  /**
   * <code>string adapter_id = 1;</code>
   * @return The adapterId.
   */
  @java.lang.Override
  public java.lang.String getAdapterId() {
    java.lang.Object ref = adapterId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      adapterId_ = s;
      return s;
    }
  }
  /**
   * <code>string adapter_id = 1;</code>
   * @return The bytes for adapterId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAdapterIdBytes() {
    java.lang.Object ref = adapterId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      adapterId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OLD_STATE_FIELD_NUMBER = 2;
  private int oldState_ = 0;
  /**
   * <code>.sdv.services.update.AdapterState old_state = 2;</code>
   * @return The enum numeric value on the wire for oldState.
   */
  @java.lang.Override public int getOldStateValue() {
    return oldState_;
  }
  /**
   * <code>.sdv.services.update.AdapterState old_state = 2;</code>
   * @return The oldState.
   */
  @java.lang.Override public sdv.services.update.AdapterState getOldState() {
    sdv.services.update.AdapterState result = sdv.services.update.AdapterState.forNumber(oldState_);
    return result == null ? sdv.services.update.AdapterState.UNRECOGNIZED : result;
  }

  public static final int NEW_STATE_FIELD_NUMBER = 3;
  private int newState_ = 0;
  /**
   * <code>.sdv.services.update.AdapterState new_state = 3;</code>
   * @return The enum numeric value on the wire for newState.
   */
  @java.lang.Override public int getNewStateValue() {
    return newState_;
  }
  /**
   * <code>.sdv.services.update.AdapterState new_state = 3;</code>
   * @return The newState.
   */
  @java.lang.Override public sdv.services.update.AdapterState getNewState() {
    sdv.services.update.AdapterState result = sdv.services.update.AdapterState.forNumber(newState_);
    return result == null ? sdv.services.update.AdapterState.UNRECOGNIZED : result;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <code>string error_message = 4;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string error_message = 4;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(adapterId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, adapterId_);
    }
    if (oldState_ != sdv.services.update.AdapterState.ADAPTER_STATE_UNKNOWN.getNumber()) {
      output.writeEnum(2, oldState_);
    }
    if (newState_ != sdv.services.update.AdapterState.ADAPTER_STATE_UNKNOWN.getNumber()) {
      output.writeEnum(3, newState_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, errorMessage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(adapterId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, adapterId_);
    }
    if (oldState_ != sdv.services.update.AdapterState.ADAPTER_STATE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, oldState_);
    }
    if (newState_ != sdv.services.update.AdapterState.ADAPTER_STATE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, newState_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, errorMessage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sdv.services.update.AdapterStateEvent)) {
      return super.equals(obj);
    }
    sdv.services.update.AdapterStateEvent other = (sdv.services.update.AdapterStateEvent) obj;

    if (!getAdapterId()
        .equals(other.getAdapterId())) return false;
    if (oldState_ != other.oldState_) return false;
    if (newState_ != other.newState_) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADAPTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAdapterId().hashCode();
    hash = (37 * hash) + OLD_STATE_FIELD_NUMBER;
    hash = (53 * hash) + oldState_;
    hash = (37 * hash) + NEW_STATE_FIELD_NUMBER;
    hash = (53 * hash) + newState_;
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sdv.services.update.AdapterStateEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.update.AdapterStateEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.update.AdapterStateEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.update.AdapterStateEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.update.AdapterStateEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.update.AdapterStateEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.update.AdapterStateEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sdv.services.update.AdapterStateEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sdv.services.update.AdapterStateEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sdv.services.update.AdapterStateEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdv.services.update.AdapterStateEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sdv.services.update.AdapterStateEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sdv.services.update.AdapterStateEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * AdapterStateEvent represents a state change event for an adapter
   * </pre>
   *
   * Protobuf type {@code sdv.services.update.AdapterStateEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sdv.services.update.AdapterStateEvent)
      sdv.services.update.AdapterStateEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sdv.services.update.UpdateServiceOuterClass.internal_static_sdv_services_update_AdapterStateEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sdv.services.update.UpdateServiceOuterClass.internal_static_sdv_services_update_AdapterStateEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sdv.services.update.AdapterStateEvent.class, sdv.services.update.AdapterStateEvent.Builder.class);
    }

    // Construct using sdv.services.update.AdapterStateEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      adapterId_ = "";
      oldState_ = 0;
      newState_ = 0;
      errorMessage_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sdv.services.update.UpdateServiceOuterClass.internal_static_sdv_services_update_AdapterStateEvent_descriptor;
    }

    @java.lang.Override
    public sdv.services.update.AdapterStateEvent getDefaultInstanceForType() {
      return sdv.services.update.AdapterStateEvent.getDefaultInstance();
    }

    @java.lang.Override
    public sdv.services.update.AdapterStateEvent build() {
      sdv.services.update.AdapterStateEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sdv.services.update.AdapterStateEvent buildPartial() {
      sdv.services.update.AdapterStateEvent result = new sdv.services.update.AdapterStateEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(sdv.services.update.AdapterStateEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.adapterId_ = adapterId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.oldState_ = oldState_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.newState_ = newState_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sdv.services.update.AdapterStateEvent) {
        return mergeFrom((sdv.services.update.AdapterStateEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sdv.services.update.AdapterStateEvent other) {
      if (other == sdv.services.update.AdapterStateEvent.getDefaultInstance()) return this;
      if (!other.getAdapterId().isEmpty()) {
        adapterId_ = other.adapterId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.oldState_ != 0) {
        setOldStateValue(other.getOldStateValue());
      }
      if (other.newState_ != 0) {
        setNewStateValue(other.getNewStateValue());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              adapterId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              oldState_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              newState_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object adapterId_ = "";
    /**
     * <code>string adapter_id = 1;</code>
     * @return The adapterId.
     */
    public java.lang.String getAdapterId() {
      java.lang.Object ref = adapterId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        adapterId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string adapter_id = 1;</code>
     * @return The bytes for adapterId.
     */
    public com.google.protobuf.ByteString
        getAdapterIdBytes() {
      java.lang.Object ref = adapterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adapterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string adapter_id = 1;</code>
     * @param value The adapterId to set.
     * @return This builder for chaining.
     */
    public Builder setAdapterId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      adapterId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string adapter_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdapterId() {
      adapterId_ = getDefaultInstance().getAdapterId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string adapter_id = 1;</code>
     * @param value The bytes for adapterId to set.
     * @return This builder for chaining.
     */
    public Builder setAdapterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      adapterId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int oldState_ = 0;
    /**
     * <code>.sdv.services.update.AdapterState old_state = 2;</code>
     * @return The enum numeric value on the wire for oldState.
     */
    @java.lang.Override public int getOldStateValue() {
      return oldState_;
    }
    /**
     * <code>.sdv.services.update.AdapterState old_state = 2;</code>
     * @param value The enum numeric value on the wire for oldState to set.
     * @return This builder for chaining.
     */
    public Builder setOldStateValue(int value) {
      oldState_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.sdv.services.update.AdapterState old_state = 2;</code>
     * @return The oldState.
     */
    @java.lang.Override
    public sdv.services.update.AdapterState getOldState() {
      sdv.services.update.AdapterState result = sdv.services.update.AdapterState.forNumber(oldState_);
      return result == null ? sdv.services.update.AdapterState.UNRECOGNIZED : result;
    }
    /**
     * <code>.sdv.services.update.AdapterState old_state = 2;</code>
     * @param value The oldState to set.
     * @return This builder for chaining.
     */
    public Builder setOldState(sdv.services.update.AdapterState value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      oldState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.sdv.services.update.AdapterState old_state = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOldState() {
      bitField0_ = (bitField0_ & ~0x00000002);
      oldState_ = 0;
      onChanged();
      return this;
    }

    private int newState_ = 0;
    /**
     * <code>.sdv.services.update.AdapterState new_state = 3;</code>
     * @return The enum numeric value on the wire for newState.
     */
    @java.lang.Override public int getNewStateValue() {
      return newState_;
    }
    /**
     * <code>.sdv.services.update.AdapterState new_state = 3;</code>
     * @param value The enum numeric value on the wire for newState to set.
     * @return This builder for chaining.
     */
    public Builder setNewStateValue(int value) {
      newState_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.sdv.services.update.AdapterState new_state = 3;</code>
     * @return The newState.
     */
    @java.lang.Override
    public sdv.services.update.AdapterState getNewState() {
      sdv.services.update.AdapterState result = sdv.services.update.AdapterState.forNumber(newState_);
      return result == null ? sdv.services.update.AdapterState.UNRECOGNIZED : result;
    }
    /**
     * <code>.sdv.services.update.AdapterState new_state = 3;</code>
     * @param value The newState to set.
     * @return This builder for chaining.
     */
    public Builder setNewState(sdv.services.update.AdapterState value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000004;
      newState_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.sdv.services.update.AdapterState new_state = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNewState() {
      bitField0_ = (bitField0_ & ~0x00000004);
      newState_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string error_message = 4;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_message = 4;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_message = 4;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 4;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sdv.services.update.AdapterStateEvent)
  }

  // @@protoc_insertion_point(class_scope:sdv.services.update.AdapterStateEvent)
  private static final sdv.services.update.AdapterStateEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sdv.services.update.AdapterStateEvent();
  }

  public static sdv.services.update.AdapterStateEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdapterStateEvent>
      PARSER = new com.google.protobuf.AbstractParser<AdapterStateEvent>() {
    @java.lang.Override
    public AdapterStateEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AdapterStateEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdapterStateEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sdv.services.update.AdapterStateEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

