// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/update_service.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package sdv.services.update;

@kotlin.jvm.JvmName("-initializeinstallAdapterRequest")
public inline fun installAdapterRequest(block: sdv.services.update.InstallAdapterRequestKt.Dsl.() -> kotlin.Unit): sdv.services.update.InstallAdapterRequest =
  sdv.services.update.InstallAdapterRequestKt.Dsl._create(sdv.services.update.InstallAdapterRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * InstallAdapterRequest contains the information needed to install an adapter
 * ```
 *
 * Protobuf type `sdv.services.update.InstallAdapterRequest`
 */
public object InstallAdapterRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: sdv.services.update.InstallAdapterRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: sdv.services.update.InstallAdapterRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): sdv.services.update.InstallAdapterRequest = _builder.build()

    /**
     * `string image_ref = 1;`
     */
    public var imageRef: kotlin.String
      @kotlin.jvm.JvmName("getImageRef")
        get() = _builder.imageRef
      @kotlin.jvm.JvmName("setImageRef")
        set(value) {
        _builder.imageRef = value
      }
    /**
     * `string image_ref = 1;`
     */
    public fun clearImageRef() {
      _builder.clearImageRef()
    }

    /**
     * `string checksum = 2;`
     */
    public var checksum: kotlin.String
      @kotlin.jvm.JvmName("getChecksum")
        get() = _builder.checksum
      @kotlin.jvm.JvmName("setChecksum")
        set(value) {
        _builder.checksum = value
      }
    /**
     * `string checksum = 2;`
     */
    public fun clearChecksum() {
      _builder.clearChecksum()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun sdv.services.update.InstallAdapterRequest.copy(block: `sdv.services.update`.InstallAdapterRequestKt.Dsl.() -> kotlin.Unit): sdv.services.update.InstallAdapterRequest =
  `sdv.services.update`.InstallAdapterRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

