// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/update_service.proto
// Protobuf Java Version: 4.33.4

package sdv.services.update;

/**
 * <pre>
 * ListAdaptersResponse contains the list of installed adapters
 * </pre>
 *
 * Protobuf type {@code sdv.services.update.ListAdaptersResponse}
 */
@com.google.protobuf.Generated
public final class ListAdaptersResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sdv.services.update.ListAdaptersResponse)
    ListAdaptersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "ListAdaptersResponse");
  }
  // Use ListAdaptersResponse.newBuilder() to construct.
  private ListAdaptersResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListAdaptersResponse() {
    adapters_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sdv.services.update.UpdateServiceOuterClass.internal_static_sdv_services_update_ListAdaptersResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sdv.services.update.UpdateServiceOuterClass.internal_static_sdv_services_update_ListAdaptersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sdv.services.update.ListAdaptersResponse.class, sdv.services.update.ListAdaptersResponse.Builder.class);
  }

  public static final int ADAPTERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<sdv.services.update.AdapterInfo> adapters_;
  /**
   * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
   */
  @java.lang.Override
  public java.util.List<sdv.services.update.AdapterInfo> getAdaptersList() {
    return adapters_;
  }
  /**
   * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends sdv.services.update.AdapterInfoOrBuilder> 
      getAdaptersOrBuilderList() {
    return adapters_;
  }
  /**
   * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
   */
  @java.lang.Override
  public int getAdaptersCount() {
    return adapters_.size();
  }
  /**
   * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
   */
  @java.lang.Override
  public sdv.services.update.AdapterInfo getAdapters(int index) {
    return adapters_.get(index);
  }
  /**
   * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
   */
  @java.lang.Override
  public sdv.services.update.AdapterInfoOrBuilder getAdaptersOrBuilder(
      int index) {
    return adapters_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < adapters_.size(); i++) {
      output.writeMessage(1, adapters_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < adapters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, adapters_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sdv.services.update.ListAdaptersResponse)) {
      return super.equals(obj);
    }
    sdv.services.update.ListAdaptersResponse other = (sdv.services.update.ListAdaptersResponse) obj;

    if (!getAdaptersList()
        .equals(other.getAdaptersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAdaptersCount() > 0) {
      hash = (37 * hash) + ADAPTERS_FIELD_NUMBER;
      hash = (53 * hash) + getAdaptersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sdv.services.update.ListAdaptersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.update.ListAdaptersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.update.ListAdaptersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.update.ListAdaptersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.update.ListAdaptersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sdv.services.update.ListAdaptersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sdv.services.update.ListAdaptersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sdv.services.update.ListAdaptersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sdv.services.update.ListAdaptersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sdv.services.update.ListAdaptersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sdv.services.update.ListAdaptersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sdv.services.update.ListAdaptersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sdv.services.update.ListAdaptersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ListAdaptersResponse contains the list of installed adapters
   * </pre>
   *
   * Protobuf type {@code sdv.services.update.ListAdaptersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sdv.services.update.ListAdaptersResponse)
      sdv.services.update.ListAdaptersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sdv.services.update.UpdateServiceOuterClass.internal_static_sdv_services_update_ListAdaptersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sdv.services.update.UpdateServiceOuterClass.internal_static_sdv_services_update_ListAdaptersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sdv.services.update.ListAdaptersResponse.class, sdv.services.update.ListAdaptersResponse.Builder.class);
    }

    // Construct using sdv.services.update.ListAdaptersResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (adaptersBuilder_ == null) {
        adapters_ = java.util.Collections.emptyList();
      } else {
        adapters_ = null;
        adaptersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sdv.services.update.UpdateServiceOuterClass.internal_static_sdv_services_update_ListAdaptersResponse_descriptor;
    }

    @java.lang.Override
    public sdv.services.update.ListAdaptersResponse getDefaultInstanceForType() {
      return sdv.services.update.ListAdaptersResponse.getDefaultInstance();
    }

    @java.lang.Override
    public sdv.services.update.ListAdaptersResponse build() {
      sdv.services.update.ListAdaptersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sdv.services.update.ListAdaptersResponse buildPartial() {
      sdv.services.update.ListAdaptersResponse result = new sdv.services.update.ListAdaptersResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(sdv.services.update.ListAdaptersResponse result) {
      if (adaptersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          adapters_ = java.util.Collections.unmodifiableList(adapters_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.adapters_ = adapters_;
      } else {
        result.adapters_ = adaptersBuilder_.build();
      }
    }

    private void buildPartial0(sdv.services.update.ListAdaptersResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sdv.services.update.ListAdaptersResponse) {
        return mergeFrom((sdv.services.update.ListAdaptersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sdv.services.update.ListAdaptersResponse other) {
      if (other == sdv.services.update.ListAdaptersResponse.getDefaultInstance()) return this;
      if (adaptersBuilder_ == null) {
        if (!other.adapters_.isEmpty()) {
          if (adapters_.isEmpty()) {
            adapters_ = other.adapters_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAdaptersIsMutable();
            adapters_.addAll(other.adapters_);
          }
          onChanged();
        }
      } else {
        if (!other.adapters_.isEmpty()) {
          if (adaptersBuilder_.isEmpty()) {
            adaptersBuilder_.dispose();
            adaptersBuilder_ = null;
            adapters_ = other.adapters_;
            bitField0_ = (bitField0_ & ~0x00000001);
            adaptersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetAdaptersFieldBuilder() : null;
          } else {
            adaptersBuilder_.addAllMessages(other.adapters_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sdv.services.update.AdapterInfo m =
                  input.readMessage(
                      sdv.services.update.AdapterInfo.parser(),
                      extensionRegistry);
              if (adaptersBuilder_ == null) {
                ensureAdaptersIsMutable();
                adapters_.add(m);
              } else {
                adaptersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<sdv.services.update.AdapterInfo> adapters_ =
      java.util.Collections.emptyList();
    private void ensureAdaptersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        adapters_ = new java.util.ArrayList<sdv.services.update.AdapterInfo>(adapters_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        sdv.services.update.AdapterInfo, sdv.services.update.AdapterInfo.Builder, sdv.services.update.AdapterInfoOrBuilder> adaptersBuilder_;

    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public java.util.List<sdv.services.update.AdapterInfo> getAdaptersList() {
      if (adaptersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(adapters_);
      } else {
        return adaptersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public int getAdaptersCount() {
      if (adaptersBuilder_ == null) {
        return adapters_.size();
      } else {
        return adaptersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public sdv.services.update.AdapterInfo getAdapters(int index) {
      if (adaptersBuilder_ == null) {
        return adapters_.get(index);
      } else {
        return adaptersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public Builder setAdapters(
        int index, sdv.services.update.AdapterInfo value) {
      if (adaptersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdaptersIsMutable();
        adapters_.set(index, value);
        onChanged();
      } else {
        adaptersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public Builder setAdapters(
        int index, sdv.services.update.AdapterInfo.Builder builderForValue) {
      if (adaptersBuilder_ == null) {
        ensureAdaptersIsMutable();
        adapters_.set(index, builderForValue.build());
        onChanged();
      } else {
        adaptersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public Builder addAdapters(sdv.services.update.AdapterInfo value) {
      if (adaptersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdaptersIsMutable();
        adapters_.add(value);
        onChanged();
      } else {
        adaptersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public Builder addAdapters(
        int index, sdv.services.update.AdapterInfo value) {
      if (adaptersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAdaptersIsMutable();
        adapters_.add(index, value);
        onChanged();
      } else {
        adaptersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public Builder addAdapters(
        sdv.services.update.AdapterInfo.Builder builderForValue) {
      if (adaptersBuilder_ == null) {
        ensureAdaptersIsMutable();
        adapters_.add(builderForValue.build());
        onChanged();
      } else {
        adaptersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public Builder addAdapters(
        int index, sdv.services.update.AdapterInfo.Builder builderForValue) {
      if (adaptersBuilder_ == null) {
        ensureAdaptersIsMutable();
        adapters_.add(index, builderForValue.build());
        onChanged();
      } else {
        adaptersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public Builder addAllAdapters(
        java.lang.Iterable<? extends sdv.services.update.AdapterInfo> values) {
      if (adaptersBuilder_ == null) {
        ensureAdaptersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, adapters_);
        onChanged();
      } else {
        adaptersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public Builder clearAdapters() {
      if (adaptersBuilder_ == null) {
        adapters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        adaptersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public Builder removeAdapters(int index) {
      if (adaptersBuilder_ == null) {
        ensureAdaptersIsMutable();
        adapters_.remove(index);
        onChanged();
      } else {
        adaptersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public sdv.services.update.AdapterInfo.Builder getAdaptersBuilder(
        int index) {
      return internalGetAdaptersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public sdv.services.update.AdapterInfoOrBuilder getAdaptersOrBuilder(
        int index) {
      if (adaptersBuilder_ == null) {
        return adapters_.get(index);  } else {
        return adaptersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public java.util.List<? extends sdv.services.update.AdapterInfoOrBuilder> 
         getAdaptersOrBuilderList() {
      if (adaptersBuilder_ != null) {
        return adaptersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(adapters_);
      }
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public sdv.services.update.AdapterInfo.Builder addAdaptersBuilder() {
      return internalGetAdaptersFieldBuilder().addBuilder(
          sdv.services.update.AdapterInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public sdv.services.update.AdapterInfo.Builder addAdaptersBuilder(
        int index) {
      return internalGetAdaptersFieldBuilder().addBuilder(
          index, sdv.services.update.AdapterInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .sdv.services.update.AdapterInfo adapters = 1;</code>
     */
    public java.util.List<sdv.services.update.AdapterInfo.Builder> 
         getAdaptersBuilderList() {
      return internalGetAdaptersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        sdv.services.update.AdapterInfo, sdv.services.update.AdapterInfo.Builder, sdv.services.update.AdapterInfoOrBuilder> 
        internalGetAdaptersFieldBuilder() {
      if (adaptersBuilder_ == null) {
        adaptersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            sdv.services.update.AdapterInfo, sdv.services.update.AdapterInfo.Builder, sdv.services.update.AdapterInfoOrBuilder>(
                adapters_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        adapters_ = null;
      }
      return adaptersBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:sdv.services.update.ListAdaptersResponse)
  }

  // @@protoc_insertion_point(class_scope:sdv.services.update.ListAdaptersResponse)
  private static final sdv.services.update.ListAdaptersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sdv.services.update.ListAdaptersResponse();
  }

  public static sdv.services.update.ListAdaptersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListAdaptersResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListAdaptersResponse>() {
    @java.lang.Override
    public ListAdaptersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListAdaptersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListAdaptersResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sdv.services.update.ListAdaptersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

