// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/update_service.proto
// Protobuf Java Version: 4.33.4

package sdv.services.update;

@com.google.protobuf.Generated
public interface UninstallAdapterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdv.services.update.UninstallAdapterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string error_message = 2;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 2;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
