// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/update_service.proto
// Protobuf Java Version: 4.33.4

package sdv.services.update;

@com.google.protobuf.Generated
public final class UpdateServiceOuterClass extends com.google.protobuf.GeneratedFile {
  private UpdateServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "UpdateServiceOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_update_AdapterInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_update_AdapterInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_update_InstallAdapterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_update_InstallAdapterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_update_InstallAdapterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_update_InstallAdapterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_update_UninstallAdapterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_update_UninstallAdapterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_update_UninstallAdapterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_update_UninstallAdapterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_update_ListAdaptersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_update_ListAdaptersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_update_ListAdaptersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_update_ListAdaptersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_update_WatchAdapterStatesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_update_WatchAdapterStatesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_services_update_AdapterStateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_services_update_AdapterStateEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035services/update_service.proto\022\023sdv.ser" +
      "vices.update\"\216\001\n\013AdapterInfo\022\022\n\nadapter_" +
      "id\030\001 \001(\t\022\021\n\timage_ref\030\002 \001(\t\022\017\n\007version\030\003" +
      " \001(\t\0220\n\005state\030\004 \001(\0162!.sdv.services.updat" +
      "e.AdapterState\022\025\n\rerror_message\030\005 \001(\t\"<\n" +
      "\025InstallAdapterRequest\022\021\n\timage_ref\030\001 \001(" +
      "\t\022\020\n\010checksum\030\002 \001(\t\"n\n\026InstallAdapterRes" +
      "ponse\022\016\n\006job_id\030\001 \001(\t\022\022\n\nadapter_id\030\002 \001(" +
      "\t\0220\n\005state\030\003 \001(\0162!.sdv.services.update.A" +
      "dapterState\"-\n\027UninstallAdapterRequest\022\022" +
      "\n\nadapter_id\030\001 \001(\t\"B\n\030UninstallAdapterRe" +
      "sponse\022\017\n\007success\030\001 \001(\010\022\025\n\rerror_message" +
      "\030\002 \001(\t\"\025\n\023ListAdaptersRequest\"J\n\024ListAda" +
      "ptersResponse\0222\n\010adapters\030\001 \003(\0132 .sdv.se" +
      "rvices.update.AdapterInfo\"0\n\031WatchAdapte" +
      "rStatesRequest\022\023\n\013adapter_ids\030\001 \003(\t\"\252\001\n\021" +
      "AdapterStateEvent\022\022\n\nadapter_id\030\001 \001(\t\0224\n" +
      "\told_state\030\002 \001(\0162!.sdv.services.update.A" +
      "dapterState\0224\n\tnew_state\030\003 \001(\0162!.sdv.ser" +
      "vices.update.AdapterState\022\025\n\rerror_messa" +
      "ge\030\004 \001(\t*\265\001\n\014AdapterState\022\031\n\025ADAPTER_STA" +
      "TE_UNKNOWN\020\000\022\035\n\031ADAPTER_STATE_DOWNLOADIN" +
      "G\020\001\022\034\n\030ADAPTER_STATE_INSTALLING\020\002\022\031\n\025ADA" +
      "PTER_STATE_RUNNING\020\003\022\031\n\025ADAPTER_STATE_ST" +
      "OPPED\020\004\022\027\n\023ADAPTER_STATE_ERROR\020\0052\300\003\n\rUpd" +
      "ateService\022i\n\016InstallAdapter\022*.sdv.servi" +
      "ces.update.InstallAdapterRequest\032+.sdv.s" +
      "ervices.update.InstallAdapterResponse\022o\n" +
      "\020UninstallAdapter\022,.sdv.services.update." +
      "UninstallAdapterRequest\032-.sdv.services.u" +
      "pdate.UninstallAdapterResponse\022c\n\014ListAd" +
      "apters\022(.sdv.services.update.ListAdapter" +
      "sRequest\032).sdv.services.update.ListAdapt" +
      "ersResponse\022n\n\022WatchAdapterStates\022..sdv." +
      "services.update.WatchAdapterStatesReques" +
      "t\032&.sdv.services.update.AdapterStateEven" +
      "t0\001BP\n\023sdv.services.updateP\001Z7github.com" +
      "/sdv-parking-demo/backend/gen/services/u" +
      "pdateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sdv_services_update_AdapterInfo_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_sdv_services_update_AdapterInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_update_AdapterInfo_descriptor,
        new java.lang.String[] { "AdapterId", "ImageRef", "Version", "State", "ErrorMessage", });
    internal_static_sdv_services_update_InstallAdapterRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_sdv_services_update_InstallAdapterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_update_InstallAdapterRequest_descriptor,
        new java.lang.String[] { "ImageRef", "Checksum", });
    internal_static_sdv_services_update_InstallAdapterResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_sdv_services_update_InstallAdapterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_update_InstallAdapterResponse_descriptor,
        new java.lang.String[] { "JobId", "AdapterId", "State", });
    internal_static_sdv_services_update_UninstallAdapterRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_sdv_services_update_UninstallAdapterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_update_UninstallAdapterRequest_descriptor,
        new java.lang.String[] { "AdapterId", });
    internal_static_sdv_services_update_UninstallAdapterResponse_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_sdv_services_update_UninstallAdapterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_update_UninstallAdapterResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorMessage", });
    internal_static_sdv_services_update_ListAdaptersRequest_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_sdv_services_update_ListAdaptersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_update_ListAdaptersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_sdv_services_update_ListAdaptersResponse_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_sdv_services_update_ListAdaptersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_update_ListAdaptersResponse_descriptor,
        new java.lang.String[] { "Adapters", });
    internal_static_sdv_services_update_WatchAdapterStatesRequest_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_sdv_services_update_WatchAdapterStatesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_update_WatchAdapterStatesRequest_descriptor,
        new java.lang.String[] { "AdapterIds", });
    internal_static_sdv_services_update_AdapterStateEvent_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_sdv_services_update_AdapterStateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_services_update_AdapterStateEvent_descriptor,
        new java.lang.String[] { "AdapterId", "OldState", "NewState", "ErrorMessage", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
