// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/update_service.proto
// Protobuf Java Version: 4.33.4

package sdv.services.update;

@com.google.protobuf.Generated
public interface WatchAdapterStatesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdv.services.update.WatchAdapterStatesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Empty = watch all
   * </pre>
   *
   * <code>repeated string adapter_ids = 1;</code>
   * @return A list containing the adapterIds.
   */
  java.util.List<java.lang.String>
      getAdapterIdsList();
  /**
   * <pre>
   * Empty = watch all
   * </pre>
   *
   * <code>repeated string adapter_ids = 1;</code>
   * @return The count of adapterIds.
   */
  int getAdapterIdsCount();
  /**
   * <pre>
   * Empty = watch all
   * </pre>
   *
   * <code>repeated string adapter_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The adapterIds at the given index.
   */
  java.lang.String getAdapterIds(int index);
  /**
   * <pre>
   * Empty = watch all
   * </pre>
   *
   * <code>repeated string adapter_ids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the adapterIds at the given index.
   */
  com.google.protobuf.ByteString
      getAdapterIdsBytes(int index);
}
