// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/error.proto
// Protobuf Java Version: 4.33.4

package com.sdv.common;

/**
 * <pre>
 * ErrorCode enum provides type-safe error codes for use in services.
 * Services should use these codes in the ErrorDetails.code field.
 * </pre>
 *
 * Protobuf enum {@code sdv.common.ErrorCode}
 */
@com.google.protobuf.Generated
public enum ErrorCode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default/unknown error
   * </pre>
   *
   * <code>ERROR_CODE_UNSPECIFIED = 0;</code>
   */
  ERROR_CODE_UNSPECIFIED(0),
  /**
   * <pre>
   * Invalid request or proto message
   * </pre>
   *
   * <code>ERROR_CODE_INVALID_REQUEST = 1;</code>
   */
  ERROR_CODE_INVALID_REQUEST(1),
  /**
   * <pre>
   * Service is not ready to handle requests
   * </pre>
   *
   * <code>ERROR_CODE_SERVICE_NOT_READY = 2;</code>
   */
  ERROR_CODE_SERVICE_NOT_READY(2),
  /**
   * <pre>
   * Container registry is unavailable
   * </pre>
   *
   * <code>ERROR_CODE_REGISTRY_UNAVAILABLE = 3;</code>
   */
  ERROR_CODE_REGISTRY_UNAVAILABLE(3),
  /**
   * <pre>
   * Container image checksum does not match expected value
   * </pre>
   *
   * <code>ERROR_CODE_CHECKSUM_MISMATCH = 4;</code>
   */
  ERROR_CODE_CHECKSUM_MISMATCH(4),
  /**
   * <pre>
   * TLS handshake or certificate error
   * </pre>
   *
   * <code>ERROR_CODE_TLS_ERROR = 5;</code>
   */
  ERROR_CODE_TLS_ERROR(5),
  /**
   * <pre>
   * Socket or network connection failed
   * </pre>
   *
   * <code>ERROR_CODE_CONNECTION_FAILED = 6;</code>
   */
  ERROR_CODE_CONNECTION_FAILED(6),
  /**
   * <pre>
   * Authentication failed
   * </pre>
   *
   * <code>ERROR_CODE_AUTH_FAILED = 7;</code>
   */
  ERROR_CODE_AUTH_FAILED(7),
  /**
   * <pre>
   * Permission denied for the requested operation
   * </pre>
   *
   * <code>ERROR_CODE_PERMISSION_DENIED = 8;</code>
   */
  ERROR_CODE_PERMISSION_DENIED(8),
  /**
   * <pre>
   * Requested resource was not found
   * </pre>
   *
   * <code>ERROR_CODE_NOT_FOUND = 9;</code>
   */
  ERROR_CODE_NOT_FOUND(9),
  /**
   * <pre>
   * Operation timed out
   * </pre>
   *
   * <code>ERROR_CODE_TIMEOUT = 10;</code>
   */
  ERROR_CODE_TIMEOUT(10),
  /**
   * <pre>
   * Internal server error
   * </pre>
   *
   * <code>ERROR_CODE_INTERNAL_ERROR = 11;</code>
   */
  ERROR_CODE_INTERNAL_ERROR(11),
  /**
   * <pre>
   * Adapter-specific errors
   * </pre>
   *
   * <code>ERROR_CODE_ADAPTER_NOT_FOUND = 12;</code>
   */
  ERROR_CODE_ADAPTER_NOT_FOUND(12),
  /**
   * <code>ERROR_CODE_ADAPTER_ALREADY_INSTALLED = 13;</code>
   */
  ERROR_CODE_ADAPTER_ALREADY_INSTALLED(13),
  /**
   * <code>ERROR_CODE_ADAPTER_INSTALL_FAILED = 14;</code>
   */
  ERROR_CODE_ADAPTER_INSTALL_FAILED(14),
  /**
   * <pre>
   * Parking session errors
   * </pre>
   *
   * <code>ERROR_CODE_SESSION_NOT_FOUND = 15;</code>
   */
  ERROR_CODE_SESSION_NOT_FOUND(15),
  /**
   * <code>ERROR_CODE_SESSION_ALREADY_ACTIVE = 16;</code>
   */
  ERROR_CODE_SESSION_ALREADY_ACTIVE(16),
  /**
   * <code>ERROR_CODE_INVALID_ZONE = 17;</code>
   */
  ERROR_CODE_INVALID_ZONE(17),
  /**
   * <pre>
   * Locking service errors
   * </pre>
   *
   * <code>ERROR_CODE_DOOR_ALREADY_LOCKED = 18;</code>
   */
  ERROR_CODE_DOOR_ALREADY_LOCKED(18),
  /**
   * <code>ERROR_CODE_DOOR_ALREADY_UNLOCKED = 19;</code>
   */
  ERROR_CODE_DOOR_ALREADY_UNLOCKED(19),
  /**
   * <code>ERROR_CODE_DOOR_OPEN = 20;</code>
   */
  ERROR_CODE_DOOR_OPEN(20),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "ErrorCode");
  }
  /**
   * <pre>
   * Default/unknown error
   * </pre>
   *
   * <code>ERROR_CODE_UNSPECIFIED = 0;</code>
   */
  public static final int ERROR_CODE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Invalid request or proto message
   * </pre>
   *
   * <code>ERROR_CODE_INVALID_REQUEST = 1;</code>
   */
  public static final int ERROR_CODE_INVALID_REQUEST_VALUE = 1;
  /**
   * <pre>
   * Service is not ready to handle requests
   * </pre>
   *
   * <code>ERROR_CODE_SERVICE_NOT_READY = 2;</code>
   */
  public static final int ERROR_CODE_SERVICE_NOT_READY_VALUE = 2;
  /**
   * <pre>
   * Container registry is unavailable
   * </pre>
   *
   * <code>ERROR_CODE_REGISTRY_UNAVAILABLE = 3;</code>
   */
  public static final int ERROR_CODE_REGISTRY_UNAVAILABLE_VALUE = 3;
  /**
   * <pre>
   * Container image checksum does not match expected value
   * </pre>
   *
   * <code>ERROR_CODE_CHECKSUM_MISMATCH = 4;</code>
   */
  public static final int ERROR_CODE_CHECKSUM_MISMATCH_VALUE = 4;
  /**
   * <pre>
   * TLS handshake or certificate error
   * </pre>
   *
   * <code>ERROR_CODE_TLS_ERROR = 5;</code>
   */
  public static final int ERROR_CODE_TLS_ERROR_VALUE = 5;
  /**
   * <pre>
   * Socket or network connection failed
   * </pre>
   *
   * <code>ERROR_CODE_CONNECTION_FAILED = 6;</code>
   */
  public static final int ERROR_CODE_CONNECTION_FAILED_VALUE = 6;
  /**
   * <pre>
   * Authentication failed
   * </pre>
   *
   * <code>ERROR_CODE_AUTH_FAILED = 7;</code>
   */
  public static final int ERROR_CODE_AUTH_FAILED_VALUE = 7;
  /**
   * <pre>
   * Permission denied for the requested operation
   * </pre>
   *
   * <code>ERROR_CODE_PERMISSION_DENIED = 8;</code>
   */
  public static final int ERROR_CODE_PERMISSION_DENIED_VALUE = 8;
  /**
   * <pre>
   * Requested resource was not found
   * </pre>
   *
   * <code>ERROR_CODE_NOT_FOUND = 9;</code>
   */
  public static final int ERROR_CODE_NOT_FOUND_VALUE = 9;
  /**
   * <pre>
   * Operation timed out
   * </pre>
   *
   * <code>ERROR_CODE_TIMEOUT = 10;</code>
   */
  public static final int ERROR_CODE_TIMEOUT_VALUE = 10;
  /**
   * <pre>
   * Internal server error
   * </pre>
   *
   * <code>ERROR_CODE_INTERNAL_ERROR = 11;</code>
   */
  public static final int ERROR_CODE_INTERNAL_ERROR_VALUE = 11;
  /**
   * <pre>
   * Adapter-specific errors
   * </pre>
   *
   * <code>ERROR_CODE_ADAPTER_NOT_FOUND = 12;</code>
   */
  public static final int ERROR_CODE_ADAPTER_NOT_FOUND_VALUE = 12;
  /**
   * <code>ERROR_CODE_ADAPTER_ALREADY_INSTALLED = 13;</code>
   */
  public static final int ERROR_CODE_ADAPTER_ALREADY_INSTALLED_VALUE = 13;
  /**
   * <code>ERROR_CODE_ADAPTER_INSTALL_FAILED = 14;</code>
   */
  public static final int ERROR_CODE_ADAPTER_INSTALL_FAILED_VALUE = 14;
  /**
   * <pre>
   * Parking session errors
   * </pre>
   *
   * <code>ERROR_CODE_SESSION_NOT_FOUND = 15;</code>
   */
  public static final int ERROR_CODE_SESSION_NOT_FOUND_VALUE = 15;
  /**
   * <code>ERROR_CODE_SESSION_ALREADY_ACTIVE = 16;</code>
   */
  public static final int ERROR_CODE_SESSION_ALREADY_ACTIVE_VALUE = 16;
  /**
   * <code>ERROR_CODE_INVALID_ZONE = 17;</code>
   */
  public static final int ERROR_CODE_INVALID_ZONE_VALUE = 17;
  /**
   * <pre>
   * Locking service errors
   * </pre>
   *
   * <code>ERROR_CODE_DOOR_ALREADY_LOCKED = 18;</code>
   */
  public static final int ERROR_CODE_DOOR_ALREADY_LOCKED_VALUE = 18;
  /**
   * <code>ERROR_CODE_DOOR_ALREADY_UNLOCKED = 19;</code>
   */
  public static final int ERROR_CODE_DOOR_ALREADY_UNLOCKED_VALUE = 19;
  /**
   * <code>ERROR_CODE_DOOR_OPEN = 20;</code>
   */
  public static final int ERROR_CODE_DOOR_OPEN_VALUE = 20;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ErrorCode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ErrorCode forNumber(int value) {
    switch (value) {
      case 0: return ERROR_CODE_UNSPECIFIED;
      case 1: return ERROR_CODE_INVALID_REQUEST;
      case 2: return ERROR_CODE_SERVICE_NOT_READY;
      case 3: return ERROR_CODE_REGISTRY_UNAVAILABLE;
      case 4: return ERROR_CODE_CHECKSUM_MISMATCH;
      case 5: return ERROR_CODE_TLS_ERROR;
      case 6: return ERROR_CODE_CONNECTION_FAILED;
      case 7: return ERROR_CODE_AUTH_FAILED;
      case 8: return ERROR_CODE_PERMISSION_DENIED;
      case 9: return ERROR_CODE_NOT_FOUND;
      case 10: return ERROR_CODE_TIMEOUT;
      case 11: return ERROR_CODE_INTERNAL_ERROR;
      case 12: return ERROR_CODE_ADAPTER_NOT_FOUND;
      case 13: return ERROR_CODE_ADAPTER_ALREADY_INSTALLED;
      case 14: return ERROR_CODE_ADAPTER_INSTALL_FAILED;
      case 15: return ERROR_CODE_SESSION_NOT_FOUND;
      case 16: return ERROR_CODE_SESSION_ALREADY_ACTIVE;
      case 17: return ERROR_CODE_INVALID_ZONE;
      case 18: return ERROR_CODE_DOOR_ALREADY_LOCKED;
      case 19: return ERROR_CODE_DOOR_ALREADY_UNLOCKED;
      case 20: return ERROR_CODE_DOOR_OPEN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ErrorCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
          public ErrorCode findValueByNumber(int number) {
            return ErrorCode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.sdv.common.Error.getDescriptor().getEnumTypes().get(0);
  }

  private static final ErrorCode[] VALUES = values();

  public static ErrorCode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:sdv.common.ErrorCode)
}

