// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/error.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.sdv.common;

@kotlin.jvm.JvmName("-initializeerrorDetails")
public inline fun errorDetails(block: com.sdv.common.ErrorDetailsKt.Dsl.() -> kotlin.Unit): com.sdv.common.ErrorDetails =
  com.sdv.common.ErrorDetailsKt.Dsl._create(com.sdv.common.ErrorDetails.newBuilder()).apply { block() }._build()
/**
 * ```
 * ErrorDetails provides domain-specific error information
 * that accompanies standard gRPC status codes.
 * ```
 *
 * Protobuf type `sdv.common.ErrorDetails`
 */
public object ErrorDetailsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.sdv.common.ErrorDetails.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.sdv.common.ErrorDetails.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.sdv.common.ErrorDetails = _builder.build()

    /**
     * ```
     * Domain-specific error code (e.g., INVALID_REQUEST, REGISTRY_UNAVAILABLE)
     * ```
     *
     * `string code = 1;`
     */
    public var code: kotlin.String
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    /**
     * ```
     * Domain-specific error code (e.g., INVALID_REQUEST, REGISTRY_UNAVAILABLE)
     * ```
     *
     * `string code = 1;`
     */
    public fun clearCode() {
      _builder.clearCode()
    }

    /**
     * ```
     * Human-readable error message
     * ```
     *
     * `string message = 2;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * ```
     * Human-readable error message
     * ```
     *
     * `string message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DetailsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Additional context as key-value pairs
     * ```
     *
     * `map<string, string> details = 3;`
     */
     public val details: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getDetailsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.detailsMap
      )
    /**
     * ```
     * Additional context as key-value pairs
     * ```
     *
     * `map<string, string> details = 3;`
     */
    @kotlin.jvm.JvmName("putDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putDetails(key, value)
       }
    /**
     * ```
     * Additional context as key-value pairs
     * ```
     *
     * `map<string, string> details = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setDetails")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * ```
     * Additional context as key-value pairs
     * ```
     *
     * `map<string, string> details = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .remove(key: kotlin.String) {
         _builder.removeDetails(key)
       }
    /**
     * ```
     * Additional context as key-value pairs
     * ```
     *
     * `map<string, string> details = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllDetails(map)
       }
    /**
     * ```
     * Additional context as key-value pairs
     * ```
     *
     * `map<string, string> details = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearDetails")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, DetailsProxy>
      .clear() {
         _builder.clearDetails()
       }

    /**
     * ```
     * Unix timestamp (milliseconds) when the error occurred
     * ```
     *
     * `int64 timestamp = 4;`
     */
    public var timestamp: kotlin.Long
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * ```
     * Unix timestamp (milliseconds) when the error occurred
     * ```
     *
     * `int64 timestamp = 4;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.sdv.common.ErrorDetails.copy(block: `com.sdv.common`.ErrorDetailsKt.Dsl.() -> kotlin.Unit): com.sdv.common.ErrorDetails =
  `com.sdv.common`.ErrorDetailsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

