// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/error.proto
// Protobuf Java Version: 4.33.4

package com.sdv.common;

@com.google.protobuf.Generated
public final class Error extends com.google.protobuf.GeneratedFile {
  private Error() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "Error");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_common_ErrorDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_common_ErrorDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdv_common_ErrorDetails_DetailsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sdv_common_ErrorDetails_DetailsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022common/error.proto\022\nsdv.common\"\250\001\n\014Err" +
      "orDetails\022\014\n\004code\030\001 \001(\t\022\017\n\007message\030\002 \001(\t" +
      "\0226\n\007details\030\003 \003(\0132%.sdv.common.ErrorDeta" +
      "ils.DetailsEntry\022\021\n\ttimestamp\030\004 \001(\003\032.\n\014D" +
      "etailsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:" +
      "\0028\001*\270\005\n\tErrorCode\022\032\n\026ERROR_CODE_UNSPECIF" +
      "IED\020\000\022\036\n\032ERROR_CODE_INVALID_REQUEST\020\001\022 \n" +
      "\034ERROR_CODE_SERVICE_NOT_READY\020\002\022#\n\037ERROR" +
      "_CODE_REGISTRY_UNAVAILABLE\020\003\022 \n\034ERROR_CO" +
      "DE_CHECKSUM_MISMATCH\020\004\022\030\n\024ERROR_CODE_TLS" +
      "_ERROR\020\005\022 \n\034ERROR_CODE_CONNECTION_FAILED" +
      "\020\006\022\032\n\026ERROR_CODE_AUTH_FAILED\020\007\022 \n\034ERROR_" +
      "CODE_PERMISSION_DENIED\020\010\022\030\n\024ERROR_CODE_N" +
      "OT_FOUND\020\t\022\026\n\022ERROR_CODE_TIMEOUT\020\n\022\035\n\031ER" +
      "ROR_CODE_INTERNAL_ERROR\020\013\022 \n\034ERROR_CODE_" +
      "ADAPTER_NOT_FOUND\020\014\022(\n$ERROR_CODE_ADAPTE" +
      "R_ALREADY_INSTALLED\020\r\022%\n!ERROR_CODE_ADAP" +
      "TER_INSTALL_FAILED\020\016\022 \n\034ERROR_CODE_SESSI" +
      "ON_NOT_FOUND\020\017\022%\n!ERROR_CODE_SESSION_ALR" +
      "EADY_ACTIVE\020\020\022\033\n\027ERROR_CODE_INVALID_ZONE" +
      "\020\021\022\"\n\036ERROR_CODE_DOOR_ALREADY_LOCKED\020\022\022$" +
      "\n ERROR_CODE_DOOR_ALREADY_UNLOCKED\020\023\022\030\n\024" +
      "ERROR_CODE_DOOR_OPEN\020\024BB\n\016com.sdv.common" +
      "P\001Z.github.com/sdv-parking-demo/backend/" +
      "gen/commonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sdv_common_ErrorDetails_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_sdv_common_ErrorDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_common_ErrorDetails_descriptor,
        new java.lang.String[] { "Code", "Message", "Details", "Timestamp", });
    internal_static_sdv_common_ErrorDetails_DetailsEntry_descriptor =
      internal_static_sdv_common_ErrorDetails_descriptor.getNestedType(0);
    internal_static_sdv_common_ErrorDetails_DetailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sdv_common_ErrorDetails_DetailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
