#!/usr/bin/env bash
# Copyright 2024 SDV Parking Demo System
# Proto generation script for all language bindings
#
# This script generates Protocol Buffer bindings for:
# - Rust (using tonic-build/prost-build)
# - Kotlin (using protoc with grpc-kotlin plugin)
# - Dart (using protoc with dart plugin)
# - Go (using protoc with grpc-go plugin)
#
# Requirements: 2.7, 4.9

set -euo pipefail

# Script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PROTO_DIR="${PROJECT_ROOT}/proto"

# Output directories (must match buf.gen.yaml)
RUST_OUT="${PROJECT_ROOT}/rhivos/shared/src/proto"
KOTLIN_OUT="${PROJECT_ROOT}/android/parking-app/app/src/main/java"
DART_OUT="${PROJECT_ROOT}/android/companion-app/lib/generated"
GO_OUT="${PROJECT_ROOT}/backend/gen"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

# Check if a command exists
check_command() {
    local cmd="$1"
    local install_hint="${2:-}"
    
    if ! command -v "$cmd" &> /dev/null; then
        log_error "Required command '$cmd' not found."
        if [[ -n "$install_hint" ]]; then
            log_error "Install hint: $install_hint"
        fi
        return 1
    fi
    return 0
}

# Check prerequisites for a specific language
check_prerequisites() {
    local lang="$1"
    
    case "$lang" in
        rust)
            check_command "cargo" "Install Rust from https://rustup.rs"
            ;;
        kotlin)
            check_command "protoc" "Install Protocol Buffers compiler: brew install protobuf"
            ;;
        dart)
            check_command "protoc" "Install Protocol Buffers compiler: brew install protobuf"
            check_command "dart" "Install Dart SDK: https://dart.dev/get-dart"
            ;;
        go)
            check_command "protoc" "Install Protocol Buffers compiler: brew install protobuf"
            check_command "go" "Install Go: https://go.dev/dl/"
            check_command "protoc-gen-go" "Install: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest"
            check_command "protoc-gen-go-grpc" "Install: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest"
            ;;
        all)
            check_prerequisites rust
            check_prerequisites kotlin
            check_prerequisites dart
            check_prerequisites go
            ;;
        *)
            log_error "Unknown language: $lang"
            return 1
            ;;
    esac
}

# Get all proto files
get_proto_files() {
    find "${PROTO_DIR}" -name "*.proto" -type f | sort
}

# Generate Rust bindings using tonic-build
generate_rust() {
    log_info "Generating Rust Protocol Buffer bindings..."
    
    # Create output directory
    mkdir -p "${RUST_OUT}"
    
    # Create build.rs for tonic-build if it doesn't exist
    local build_rs="${PROJECT_ROOT}/rhivos/shared/build.rs"
    
    cat > "${build_rs}" << 'EOF'
// Build script for generating Rust Protocol Buffer bindings
// This file is auto-generated by scripts/generate-proto.sh

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let proto_root = std::path::Path::new("../../proto");
    
    // Collect all proto files
    let proto_files: Vec<_> = walkdir::WalkDir::new(proto_root)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "proto"))
        .map(|e| e.path().to_path_buf())
        .collect();
    
    // Configure tonic-build
    tonic_build::configure()
        .build_server(true)
        .build_client(true)
        .out_dir("src/proto")
        .compile(&proto_files, &[proto_root])?;
    
    // Re-run if any proto file changes
    for proto in &proto_files {
        println!("cargo:rerun-if-changed={}", proto.display());
    }
    
    Ok(())
}
EOF

    # Ensure shared/Cargo.toml has build dependencies
    local cargo_toml="${PROJECT_ROOT}/rhivos/shared/Cargo.toml"
    if [[ -f "$cargo_toml" ]]; then
        # Check if build-dependencies section exists
        if ! grep -q "\[build-dependencies\]" "$cargo_toml"; then
            cat >> "$cargo_toml" << 'EOF'

[build-dependencies]
tonic-build = "0.10"
walkdir = "2.4"
EOF
            log_info "Added build dependencies to rhivos/shared/Cargo.toml"
        fi
    fi
    
    # Create mod.rs for the proto module
    cat > "${RUST_OUT}/mod.rs" << 'EOF'
// Auto-generated Protocol Buffer module
// This file is regenerated by scripts/generate-proto.sh

// Common types
pub mod sdv {
    pub mod common {
        include!("sdv.common.rs");
    }
    
    pub mod vss {
        include!("sdv.vss.rs");
    }
    
    pub mod services {
        pub mod databroker {
            include!("sdv.services.databroker.rs");
        }
        
        pub mod update {
            include!("sdv.services.update.rs");
        }
        
        pub mod parking {
            include!("sdv.services.parking.rs");
        }
        
        pub mod locking {
            include!("sdv.services.locking.rs");
        }
    }
}
EOF

    # Run cargo build to generate the files
    log_info "Running cargo build to generate Rust bindings..."
    (cd "${PROJECT_ROOT}/rhivos" && cargo build -p shared 2>&1) || {
        log_warn "Cargo build encountered issues. Generated files may need manual review."
        log_info "You can regenerate by running: cd rhivos && cargo build -p shared"
    }
    
    log_success "Rust bindings generated in ${RUST_OUT}"
}

# Generate Kotlin bindings using protoc with grpc-kotlin plugin
generate_kotlin() {
    log_info "Generating Kotlin Protocol Buffer bindings..."
    
    # Create output directory
    mkdir -p "${KOTLIN_OUT}"
    
    # Copy proto files to Android project for Gradle protobuf plugin
    local android_proto_dir="${PROJECT_ROOT}/android/parking-app/src/main/proto"
    mkdir -p "${android_proto_dir}"
    
    # Copy all proto files maintaining directory structure
    cp -r "${PROTO_DIR}"/* "${android_proto_dir}/"
    
    log_info "Proto files copied to ${android_proto_dir}"
    log_info "Kotlin bindings will be generated by Gradle protobuf plugin during build"
    log_info "Run: cd android/parking-app && ./gradlew generateProto"
    
    # If protoc and plugins are available, generate directly
    if command -v protoc &> /dev/null; then
        local kotlin_grpc_out="${KOTLIN_OUT}/sdv"
        mkdir -p "${kotlin_grpc_out}"
        
        # Check for grpc-kotlin plugin
        local grpc_kotlin_plugin=""
        if command -v protoc-gen-grpc-kotlin &> /dev/null; then
            grpc_kotlin_plugin="--grpc-kotlin_out=${kotlin_grpc_out}"
        else
            log_warn "protoc-gen-grpc-kotlin not found. gRPC stubs will be generated by Gradle."
        fi
        
        # Generate Java/Kotlin protobuf classes
        protoc \
            --proto_path="${PROTO_DIR}" \
            --proto_path="${PROJECT_ROOT}" \
            --java_out="${KOTLIN_OUT}" \
            --kotlin_out="${KOTLIN_OUT}" \
            ${grpc_kotlin_plugin} \
            $(get_proto_files) 2>&1 || {
                log_warn "Direct protoc generation had issues. Gradle will handle generation."
            }
    fi
    
    log_success "Kotlin proto files prepared in ${android_proto_dir}"
}

# Generate Dart bindings using protoc with dart plugin
generate_dart() {
    log_info "Generating Dart Protocol Buffer bindings..."
    
    # Create output directory
    mkdir -p "${DART_OUT}"
    
    # Check for protoc-gen-dart
    local dart_plugin=""
    if command -v protoc-gen-dart &> /dev/null; then
        dart_plugin="protoc-gen-dart"
    elif dart pub global list 2>/dev/null | grep -q protoc_plugin; then
        dart_plugin="${HOME}/.pub-cache/bin/protoc-gen-dart"
    else
        log_warn "protoc-gen-dart not found. Installing via dart pub..."
        dart pub global activate protoc_plugin 2>&1 || {
            log_error "Failed to install protoc_plugin. Install manually: dart pub global activate protoc_plugin"
            return 1
        }
        dart_plugin="${HOME}/.pub-cache/bin/protoc-gen-dart"
    fi
    
    # Generate Dart files
    local proto_files
    proto_files=$(get_proto_files)
    
    for proto_file in $proto_files; do
        local relative_path="${proto_file#${PROTO_DIR}/}"
        local output_subdir="${DART_OUT}/$(dirname "$relative_path")"
        mkdir -p "$output_subdir"
        
        protoc \
            --proto_path="${PROTO_DIR}" \
            --dart_out="grpc:${DART_OUT}" \
            "$proto_file" 2>&1 || {
                log_warn "Failed to generate Dart bindings for $proto_file"
            }
    done
    
    # Create barrel file for easy imports
    create_dart_barrel_file
    
    log_success "Dart bindings generated in ${DART_OUT}"
}

# Generate Go bindings using protoc with grpc-go plugin
generate_go() {
    log_info "Generating Go Protocol Buffer bindings..."
    
    # Create output directory
    mkdir -p "${GO_OUT}"
    
    # Ensure Go plugins are installed
    if ! command -v protoc-gen-go &> /dev/null; then
        log_info "Installing protoc-gen-go..."
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    fi
    
    if ! command -v protoc-gen-go-grpc &> /dev/null; then
        log_info "Installing protoc-gen-go-grpc..."
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    fi
    
    # Clean existing generated files
    rm -rf "${GO_OUT}"/*
    
    # Generate Go files - use module mode to respect go_package paths
    local proto_files
    proto_files=$(get_proto_files)
    
    for proto_file in $proto_files; do
        protoc \
            --proto_path="${PROTO_DIR}" \
            --go_out="${GO_OUT}" \
            --go_opt=module=github.com/sdv-parking-demo/backend/gen \
            --go-grpc_out="${GO_OUT}" \
            --go-grpc_opt=module=github.com/sdv-parking-demo/backend/gen \
            "$proto_file" 2>&1 || {
                log_warn "Failed to generate Go bindings for $proto_file"
            }
    done
    
    log_success "Go bindings generated in ${GO_OUT}"
}

# Run buf lint on proto files
lint_protos() {
    log_info "Linting Protocol Buffer files..."
    
    if command -v buf &> /dev/null; then
        (cd "${PROTO_DIR}" && buf lint) || {
            log_warn "Buf lint found issues. Review and fix proto files."
            return 1
        }
        log_success "Proto files passed linting"
    else
        log_warn "buf not found. Skipping lint. Install: https://buf.build/docs/installation"
        
        # Fallback to protoc --lint if available
        if command -v protoc &> /dev/null; then
            log_info "Using protoc for basic validation..."
            local proto_files
            proto_files=$(get_proto_files)
            
            for proto_file in $proto_files; do
                protoc --proto_path="${PROTO_DIR}" --proto_path="${PROJECT_ROOT}" \
                    -o /dev/null "$proto_file" 2>&1 || {
                    log_error "Proto validation failed for $proto_file"
                    return 1
                }
            done
            log_success "Proto files are syntactically valid"
        fi
    fi
}

# Generate all language bindings
generate_all() {
    log_info "Generating Protocol Buffer bindings for all languages..."
    
    # Lint first
    lint_protos || log_warn "Continuing despite lint warnings..."
    
    # Check if buf is available for streamlined generation
    if command -v buf &> /dev/null; then
        log_info "Using buf for Kotlin, Dart, and Go generation..."
        generate_with_buf
        # Rust still needs tonic-build
        generate_rust
    else
        log_warn "buf not found. Using protoc directly for all languages."
        log_info "For better results, install buf: https://buf.build/docs/installation"
        # Generate for each language using protoc
        generate_rust
        generate_kotlin
        generate_dart
        generate_go
    fi
    
    log_success "All Protocol Buffer bindings generated successfully!"
}

# Generate using buf (for Kotlin, Dart, Go)
generate_with_buf() {
    log_info "Running buf generate for Kotlin, Dart, and Go..."
    
    # Create output directories
    mkdir -p "${KOTLIN_OUT}"
    mkdir -p "${DART_OUT}"
    mkdir -p "${GO_OUT}"
    
    # Run buf generate from proto directory
    (cd "${PROTO_DIR}" && buf generate) || {
        log_error "buf generate failed"
        return 1
    }
    
    # Create Dart barrel file for easy imports
    create_dart_barrel_file
    
    log_success "buf generate completed successfully"
}

# Create Dart barrel file for easy imports
create_dart_barrel_file() {
    cat > "${DART_OUT}/proto.dart" << 'EOF'
// Auto-generated Protocol Buffer exports
// This file is regenerated by scripts/generate-proto.sh
//
// Usage: import 'package:companion_app/generated/proto.dart';

// Common types
export 'common/error.pb.dart';
export 'common/error.pbenum.dart';
export 'common/error.pbjson.dart';

// VSS signals
export 'vss/signals.pb.dart';
export 'vss/signals.pbenum.dart';
export 'vss/signals.pbjson.dart';

// Services
export 'services/databroker.pb.dart';
export 'services/databroker.pbgrpc.dart';

export 'services/update_service.pb.dart';
export 'services/update_service.pbgrpc.dart';

export 'services/parking_adaptor.pb.dart';
export 'services/parking_adaptor.pbgrpc.dart';

export 'services/locking_service.pb.dart';
export 'services/locking_service.pbgrpc.dart';
EOF
}

# Clean generated files
clean() {
    log_info "Cleaning generated Protocol Buffer files..."
    
    rm -rf "${RUST_OUT}" 2>/dev/null || true
    rm -rf "${KOTLIN_OUT}/sdv" 2>/dev/null || true
    rm -rf "${KOTLIN_OUT}/com/sdv" 2>/dev/null || true
    rm -rf "${DART_OUT}" 2>/dev/null || true
    rm -rf "${GO_OUT}" 2>/dev/null || true
    rm -rf "${PROJECT_ROOT}/android/parking-app/src/main/proto" 2>/dev/null || true
    # Also clean old Dart output location if it exists
    rm -rf "${PROJECT_ROOT}/android/companion-app/lib/proto" 2>/dev/null || true
    
    log_success "Generated files cleaned"
}

# Print usage information
usage() {
    cat << EOF
Usage: $(basename "$0") [COMMAND]

Generate Protocol Buffer bindings for the SDV Parking Demo System.

Commands:
    rust        Generate Rust bindings (using tonic-build)
    kotlin      Generate Kotlin bindings (using protoc with grpc-kotlin)
    dart        Generate Dart bindings (using protoc with dart plugin)
    go          Generate Go bindings (using protoc with grpc-go)
    all         Generate bindings for all languages (default)
    lint        Lint proto files using buf or protoc
    clean       Remove all generated files
    help        Show this help message

Examples:
    $(basename "$0")           # Generate all bindings
    $(basename "$0") rust      # Generate only Rust bindings
    $(basename "$0") lint      # Lint proto files
    $(basename "$0") clean     # Clean generated files

Environment Variables:
    PROTO_DIR       Override proto source directory
    RUST_OUT        Override Rust output directory
    KOTLIN_OUT      Override Kotlin output directory
    DART_OUT        Override Dart output directory
    GO_OUT          Override Go output directory

EOF
}

# Main entry point
main() {
    local command="${1:-all}"
    
    case "$command" in
        rust)
            check_prerequisites rust && generate_rust
            ;;
        kotlin)
            check_prerequisites kotlin && generate_kotlin
            ;;
        dart)
            check_prerequisites dart && generate_dart
            ;;
        go)
            check_prerequisites go && generate_go
            ;;
        all)
            generate_all
            ;;
        lint)
            lint_protos
            ;;
        clean)
            clean
            ;;
        help|--help|-h)
            usage
            ;;
        *)
            log_error "Unknown command: $command"
            usage
            exit 1
            ;;
    esac
}

# Run main function
main "$@"
