// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/databroker.proto
// Protobuf Java Version: 4.33.4

package com.sdv.services.databroker;

/**
 * <pre>
 * Request to get current values of signals
 * </pre>
 *
 * Protobuf type {@code sdv.services.databroker.GetSignalRequest}
 */
@com.google.protobuf.Generated
public final class GetSignalRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sdv.services.databroker.GetSignalRequest)
    GetSignalRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "GetSignalRequest");
  }
  // Use GetSignalRequest.newBuilder() to construct.
  private GetSignalRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetSignalRequest() {
    signalPaths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sdv.services.databroker.Databroker.internal_static_sdv_services_databroker_GetSignalRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sdv.services.databroker.Databroker.internal_static_sdv_services_databroker_GetSignalRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sdv.services.databroker.GetSignalRequest.class, com.sdv.services.databroker.GetSignalRequest.Builder.class);
  }

  public static final int SIGNAL_PATHS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList signalPaths_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
   * </pre>
   *
   * <code>repeated string signal_paths = 1;</code>
   * @return A list containing the signalPaths.
   */
  public com.google.protobuf.ProtocolStringList
      getSignalPathsList() {
    return signalPaths_;
  }
  /**
   * <pre>
   * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
   * </pre>
   *
   * <code>repeated string signal_paths = 1;</code>
   * @return The count of signalPaths.
   */
  public int getSignalPathsCount() {
    return signalPaths_.size();
  }
  /**
   * <pre>
   * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
   * </pre>
   *
   * <code>repeated string signal_paths = 1;</code>
   * @param index The index of the element to return.
   * @return The signalPaths at the given index.
   */
  public java.lang.String getSignalPaths(int index) {
    return signalPaths_.get(index);
  }
  /**
   * <pre>
   * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
   * </pre>
   *
   * <code>repeated string signal_paths = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the signalPaths at the given index.
   */
  public com.google.protobuf.ByteString
      getSignalPathsBytes(int index) {
    return signalPaths_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < signalPaths_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, signalPaths_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < signalPaths_.size(); i++) {
        dataSize += computeStringSizeNoTag(signalPaths_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSignalPathsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sdv.services.databroker.GetSignalRequest)) {
      return super.equals(obj);
    }
    com.sdv.services.databroker.GetSignalRequest other = (com.sdv.services.databroker.GetSignalRequest) obj;

    if (!getSignalPathsList()
        .equals(other.getSignalPathsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSignalPathsCount() > 0) {
      hash = (37 * hash) + SIGNAL_PATHS_FIELD_NUMBER;
      hash = (53 * hash) + getSignalPathsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sdv.services.databroker.GetSignalRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sdv.services.databroker.GetSignalRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sdv.services.databroker.GetSignalRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sdv.services.databroker.GetSignalRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sdv.services.databroker.GetSignalRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sdv.services.databroker.GetSignalRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sdv.services.databroker.GetSignalRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sdv.services.databroker.GetSignalRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sdv.services.databroker.GetSignalRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sdv.services.databroker.GetSignalRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sdv.services.databroker.GetSignalRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sdv.services.databroker.GetSignalRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sdv.services.databroker.GetSignalRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request to get current values of signals
   * </pre>
   *
   * Protobuf type {@code sdv.services.databroker.GetSignalRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sdv.services.databroker.GetSignalRequest)
      com.sdv.services.databroker.GetSignalRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sdv.services.databroker.Databroker.internal_static_sdv_services_databroker_GetSignalRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sdv.services.databroker.Databroker.internal_static_sdv_services_databroker_GetSignalRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sdv.services.databroker.GetSignalRequest.class, com.sdv.services.databroker.GetSignalRequest.Builder.class);
    }

    // Construct using com.sdv.services.databroker.GetSignalRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      signalPaths_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sdv.services.databroker.Databroker.internal_static_sdv_services_databroker_GetSignalRequest_descriptor;
    }

    @java.lang.Override
    public com.sdv.services.databroker.GetSignalRequest getDefaultInstanceForType() {
      return com.sdv.services.databroker.GetSignalRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sdv.services.databroker.GetSignalRequest build() {
      com.sdv.services.databroker.GetSignalRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sdv.services.databroker.GetSignalRequest buildPartial() {
      com.sdv.services.databroker.GetSignalRequest result = new com.sdv.services.databroker.GetSignalRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sdv.services.databroker.GetSignalRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        signalPaths_.makeImmutable();
        result.signalPaths_ = signalPaths_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sdv.services.databroker.GetSignalRequest) {
        return mergeFrom((com.sdv.services.databroker.GetSignalRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sdv.services.databroker.GetSignalRequest other) {
      if (other == com.sdv.services.databroker.GetSignalRequest.getDefaultInstance()) return this;
      if (!other.signalPaths_.isEmpty()) {
        if (signalPaths_.isEmpty()) {
          signalPaths_ = other.signalPaths_;
          bitField0_ |= 0x00000001;
        } else {
          ensureSignalPathsIsMutable();
          signalPaths_.addAll(other.signalPaths_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureSignalPathsIsMutable();
              signalPaths_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList signalPaths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureSignalPathsIsMutable() {
      if (!signalPaths_.isModifiable()) {
        signalPaths_ = new com.google.protobuf.LazyStringArrayList(signalPaths_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>repeated string signal_paths = 1;</code>
     * @return A list containing the signalPaths.
     */
    public com.google.protobuf.ProtocolStringList
        getSignalPathsList() {
      signalPaths_.makeImmutable();
      return signalPaths_;
    }
    /**
     * <pre>
     * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>repeated string signal_paths = 1;</code>
     * @return The count of signalPaths.
     */
    public int getSignalPathsCount() {
      return signalPaths_.size();
    }
    /**
     * <pre>
     * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>repeated string signal_paths = 1;</code>
     * @param index The index of the element to return.
     * @return The signalPaths at the given index.
     */
    public java.lang.String getSignalPaths(int index) {
      return signalPaths_.get(index);
    }
    /**
     * <pre>
     * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>repeated string signal_paths = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the signalPaths at the given index.
     */
    public com.google.protobuf.ByteString
        getSignalPathsBytes(int index) {
      return signalPaths_.getByteString(index);
    }
    /**
     * <pre>
     * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>repeated string signal_paths = 1;</code>
     * @param index The index to set the value at.
     * @param value The signalPaths to set.
     * @return This builder for chaining.
     */
    public Builder setSignalPaths(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSignalPathsIsMutable();
      signalPaths_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>repeated string signal_paths = 1;</code>
     * @param value The signalPaths to add.
     * @return This builder for chaining.
     */
    public Builder addSignalPaths(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSignalPathsIsMutable();
      signalPaths_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>repeated string signal_paths = 1;</code>
     * @param values The signalPaths to add.
     * @return This builder for chaining.
     */
    public Builder addAllSignalPaths(
        java.lang.Iterable<java.lang.String> values) {
      ensureSignalPathsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, signalPaths_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>repeated string signal_paths = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignalPaths() {
      signalPaths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * VSS signal paths to retrieve (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>repeated string signal_paths = 1;</code>
     * @param value The bytes of the signalPaths to add.
     * @return This builder for chaining.
     */
    public Builder addSignalPathsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureSignalPathsIsMutable();
      signalPaths_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sdv.services.databroker.GetSignalRequest)
  }

  // @@protoc_insertion_point(class_scope:sdv.services.databroker.GetSignalRequest)
  private static final com.sdv.services.databroker.GetSignalRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sdv.services.databroker.GetSignalRequest();
  }

  public static com.sdv.services.databroker.GetSignalRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSignalRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetSignalRequest>() {
    @java.lang.Override
    public GetSignalRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetSignalRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSignalRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sdv.services.databroker.GetSignalRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

