// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/databroker.proto
// Protobuf Java Version: 4.33.4

package com.sdv.services.databroker;

/**
 * <pre>
 * Request to set a signal value
 * </pre>
 *
 * Protobuf type {@code sdv.services.databroker.SetSignalRequest}
 */
@com.google.protobuf.Generated
public final class SetSignalRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sdv.services.databroker.SetSignalRequest)
    SetSignalRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "SetSignalRequest");
  }
  // Use SetSignalRequest.newBuilder() to construct.
  private SetSignalRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SetSignalRequest() {
    signalPath_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sdv.services.databroker.Databroker.internal_static_sdv_services_databroker_SetSignalRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sdv.services.databroker.Databroker.internal_static_sdv_services_databroker_SetSignalRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sdv.services.databroker.SetSignalRequest.class, com.sdv.services.databroker.SetSignalRequest.Builder.class);
  }

  private int bitField0_;
  public static final int SIGNAL_PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object signalPath_ = "";
  /**
   * <pre>
   * VSS signal path to set (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
   * </pre>
   *
   * <code>string signal_path = 1;</code>
   * @return The signalPath.
   */
  @java.lang.Override
  public java.lang.String getSignalPath() {
    java.lang.Object ref = signalPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      signalPath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * VSS signal path to set (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
   * </pre>
   *
   * <code>string signal_path = 1;</code>
   * @return The bytes for signalPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSignalPathBytes() {
    java.lang.Object ref = signalPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signalPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNAL_FIELD_NUMBER = 2;
  private sdv.vss.Signals.VehicleSignal signal_;
  /**
   * <pre>
   * Signal value to set
   * </pre>
   *
   * <code>.sdv.vss.VehicleSignal signal = 2;</code>
   * @return Whether the signal field is set.
   */
  @java.lang.Override
  public boolean hasSignal() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Signal value to set
   * </pre>
   *
   * <code>.sdv.vss.VehicleSignal signal = 2;</code>
   * @return The signal.
   */
  @java.lang.Override
  public sdv.vss.Signals.VehicleSignal getSignal() {
    return signal_ == null ? sdv.vss.Signals.VehicleSignal.getDefaultInstance() : signal_;
  }
  /**
   * <pre>
   * Signal value to set
   * </pre>
   *
   * <code>.sdv.vss.VehicleSignal signal = 2;</code>
   */
  @java.lang.Override
  public sdv.vss.Signals.VehicleSignalOrBuilder getSignalOrBuilder() {
    return signal_ == null ? sdv.vss.Signals.VehicleSignal.getDefaultInstance() : signal_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(signalPath_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, signalPath_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getSignal());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(signalPath_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, signalPath_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSignal());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sdv.services.databroker.SetSignalRequest)) {
      return super.equals(obj);
    }
    com.sdv.services.databroker.SetSignalRequest other = (com.sdv.services.databroker.SetSignalRequest) obj;

    if (!getSignalPath()
        .equals(other.getSignalPath())) return false;
    if (hasSignal() != other.hasSignal()) return false;
    if (hasSignal()) {
      if (!getSignal()
          .equals(other.getSignal())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIGNAL_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getSignalPath().hashCode();
    if (hasSignal()) {
      hash = (37 * hash) + SIGNAL_FIELD_NUMBER;
      hash = (53 * hash) + getSignal().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sdv.services.databroker.SetSignalRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sdv.services.databroker.SetSignalRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sdv.services.databroker.SetSignalRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sdv.services.databroker.SetSignalRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sdv.services.databroker.SetSignalRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sdv.services.databroker.SetSignalRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sdv.services.databroker.SetSignalRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sdv.services.databroker.SetSignalRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sdv.services.databroker.SetSignalRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sdv.services.databroker.SetSignalRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sdv.services.databroker.SetSignalRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.sdv.services.databroker.SetSignalRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sdv.services.databroker.SetSignalRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request to set a signal value
   * </pre>
   *
   * Protobuf type {@code sdv.services.databroker.SetSignalRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sdv.services.databroker.SetSignalRequest)
      com.sdv.services.databroker.SetSignalRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sdv.services.databroker.Databroker.internal_static_sdv_services_databroker_SetSignalRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sdv.services.databroker.Databroker.internal_static_sdv_services_databroker_SetSignalRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sdv.services.databroker.SetSignalRequest.class, com.sdv.services.databroker.SetSignalRequest.Builder.class);
    }

    // Construct using com.sdv.services.databroker.SetSignalRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetSignalFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      signalPath_ = "";
      signal_ = null;
      if (signalBuilder_ != null) {
        signalBuilder_.dispose();
        signalBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sdv.services.databroker.Databroker.internal_static_sdv_services_databroker_SetSignalRequest_descriptor;
    }

    @java.lang.Override
    public com.sdv.services.databroker.SetSignalRequest getDefaultInstanceForType() {
      return com.sdv.services.databroker.SetSignalRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sdv.services.databroker.SetSignalRequest build() {
      com.sdv.services.databroker.SetSignalRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sdv.services.databroker.SetSignalRequest buildPartial() {
      com.sdv.services.databroker.SetSignalRequest result = new com.sdv.services.databroker.SetSignalRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sdv.services.databroker.SetSignalRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.signalPath_ = signalPath_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.signal_ = signalBuilder_ == null
            ? signal_
            : signalBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sdv.services.databroker.SetSignalRequest) {
        return mergeFrom((com.sdv.services.databroker.SetSignalRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sdv.services.databroker.SetSignalRequest other) {
      if (other == com.sdv.services.databroker.SetSignalRequest.getDefaultInstance()) return this;
      if (!other.getSignalPath().isEmpty()) {
        signalPath_ = other.signalPath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasSignal()) {
        mergeSignal(other.getSignal());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              signalPath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetSignalFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object signalPath_ = "";
    /**
     * <pre>
     * VSS signal path to set (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>string signal_path = 1;</code>
     * @return The signalPath.
     */
    public java.lang.String getSignalPath() {
      java.lang.Object ref = signalPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signalPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * VSS signal path to set (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>string signal_path = 1;</code>
     * @return The bytes for signalPath.
     */
    public com.google.protobuf.ByteString
        getSignalPathBytes() {
      java.lang.Object ref = signalPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signalPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * VSS signal path to set (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>string signal_path = 1;</code>
     * @param value The signalPath to set.
     * @return This builder for chaining.
     */
    public Builder setSignalPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      signalPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * VSS signal path to set (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>string signal_path = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignalPath() {
      signalPath_ = getDefaultInstance().getSignalPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * VSS signal path to set (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * </pre>
     *
     * <code>string signal_path = 1;</code>
     * @param value The bytes for signalPath to set.
     * @return This builder for chaining.
     */
    public Builder setSignalPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      signalPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private sdv.vss.Signals.VehicleSignal signal_;
    private com.google.protobuf.SingleFieldBuilder<
        sdv.vss.Signals.VehicleSignal, sdv.vss.Signals.VehicleSignal.Builder, sdv.vss.Signals.VehicleSignalOrBuilder> signalBuilder_;
    /**
     * <pre>
     * Signal value to set
     * </pre>
     *
     * <code>.sdv.vss.VehicleSignal signal = 2;</code>
     * @return Whether the signal field is set.
     */
    public boolean hasSignal() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Signal value to set
     * </pre>
     *
     * <code>.sdv.vss.VehicleSignal signal = 2;</code>
     * @return The signal.
     */
    public sdv.vss.Signals.VehicleSignal getSignal() {
      if (signalBuilder_ == null) {
        return signal_ == null ? sdv.vss.Signals.VehicleSignal.getDefaultInstance() : signal_;
      } else {
        return signalBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Signal value to set
     * </pre>
     *
     * <code>.sdv.vss.VehicleSignal signal = 2;</code>
     */
    public Builder setSignal(sdv.vss.Signals.VehicleSignal value) {
      if (signalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        signal_ = value;
      } else {
        signalBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Signal value to set
     * </pre>
     *
     * <code>.sdv.vss.VehicleSignal signal = 2;</code>
     */
    public Builder setSignal(
        sdv.vss.Signals.VehicleSignal.Builder builderForValue) {
      if (signalBuilder_ == null) {
        signal_ = builderForValue.build();
      } else {
        signalBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Signal value to set
     * </pre>
     *
     * <code>.sdv.vss.VehicleSignal signal = 2;</code>
     */
    public Builder mergeSignal(sdv.vss.Signals.VehicleSignal value) {
      if (signalBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          signal_ != null &&
          signal_ != sdv.vss.Signals.VehicleSignal.getDefaultInstance()) {
          getSignalBuilder().mergeFrom(value);
        } else {
          signal_ = value;
        }
      } else {
        signalBuilder_.mergeFrom(value);
      }
      if (signal_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Signal value to set
     * </pre>
     *
     * <code>.sdv.vss.VehicleSignal signal = 2;</code>
     */
    public Builder clearSignal() {
      bitField0_ = (bitField0_ & ~0x00000002);
      signal_ = null;
      if (signalBuilder_ != null) {
        signalBuilder_.dispose();
        signalBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Signal value to set
     * </pre>
     *
     * <code>.sdv.vss.VehicleSignal signal = 2;</code>
     */
    public sdv.vss.Signals.VehicleSignal.Builder getSignalBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetSignalFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Signal value to set
     * </pre>
     *
     * <code>.sdv.vss.VehicleSignal signal = 2;</code>
     */
    public sdv.vss.Signals.VehicleSignalOrBuilder getSignalOrBuilder() {
      if (signalBuilder_ != null) {
        return signalBuilder_.getMessageOrBuilder();
      } else {
        return signal_ == null ?
            sdv.vss.Signals.VehicleSignal.getDefaultInstance() : signal_;
      }
    }
    /**
     * <pre>
     * Signal value to set
     * </pre>
     *
     * <code>.sdv.vss.VehicleSignal signal = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        sdv.vss.Signals.VehicleSignal, sdv.vss.Signals.VehicleSignal.Builder, sdv.vss.Signals.VehicleSignalOrBuilder> 
        internalGetSignalFieldBuilder() {
      if (signalBuilder_ == null) {
        signalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            sdv.vss.Signals.VehicleSignal, sdv.vss.Signals.VehicleSignal.Builder, sdv.vss.Signals.VehicleSignalOrBuilder>(
                getSignal(),
                getParentForChildren(),
                isClean());
        signal_ = null;
      }
      return signalBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:sdv.services.databroker.SetSignalRequest)
  }

  // @@protoc_insertion_point(class_scope:sdv.services.databroker.SetSignalRequest)
  private static final com.sdv.services.databroker.SetSignalRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sdv.services.databroker.SetSignalRequest();
  }

  public static com.sdv.services.databroker.SetSignalRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetSignalRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetSignalRequest>() {
    @java.lang.Override
    public SetSignalRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SetSignalRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetSignalRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sdv.services.databroker.SetSignalRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

