// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/databroker.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.sdv.services.databroker;

@kotlin.jvm.JvmName("-initializesetSignalRequest")
public inline fun setSignalRequest(block: com.sdv.services.databroker.SetSignalRequestKt.Dsl.() -> kotlin.Unit): com.sdv.services.databroker.SetSignalRequest =
  com.sdv.services.databroker.SetSignalRequestKt.Dsl._create(com.sdv.services.databroker.SetSignalRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * Request to set a signal value
 * ```
 *
 * Protobuf type `sdv.services.databroker.SetSignalRequest`
 */
public object SetSignalRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.sdv.services.databroker.SetSignalRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.sdv.services.databroker.SetSignalRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.sdv.services.databroker.SetSignalRequest = _builder.build()

    /**
     * ```
     * VSS signal path to set (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * ```
     *
     * `string signal_path = 1;`
     */
    public var signalPath: kotlin.String
      @kotlin.jvm.JvmName("getSignalPath")
        get() = _builder.signalPath
      @kotlin.jvm.JvmName("setSignalPath")
        set(value) {
        _builder.signalPath = value
      }
    /**
     * ```
     * VSS signal path to set (e.g., "Vehicle.Cabin.Door.Row1.DriverSide.IsLocked")
     * ```
     *
     * `string signal_path = 1;`
     */
    public fun clearSignalPath() {
      _builder.clearSignalPath()
    }

    /**
     * ```
     * Signal value to set
     * ```
     *
     * `.sdv.vss.VehicleSignal signal = 2;`
     */
    public var signal: sdv.vss.Signals.VehicleSignal
      @kotlin.jvm.JvmName("getSignal")
        get() = _builder.signal
      @kotlin.jvm.JvmName("setSignal")
        set(value) {
        _builder.signal = value
      }
    /**
     * ```
     * Signal value to set
     * ```
     *
     * `.sdv.vss.VehicleSignal signal = 2;`
     */
    public fun clearSignal() {
      _builder.clearSignal()
    }
    /**
     * ```
     * Signal value to set
     * ```
     *
     * `.sdv.vss.VehicleSignal signal = 2;`
     * @return Whether the signal field is set.
     */
    public fun hasSignal(): kotlin.Boolean {
      return _builder.hasSignal()
    }

    public val SetSignalRequestKt.Dsl.signalOrNull: sdv.vss.Signals.VehicleSignal?
      get() = _builder.signalOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.sdv.services.databroker.SetSignalRequest.copy(block: `com.sdv.services.databroker`.SetSignalRequestKt.Dsl.() -> kotlin.Unit): com.sdv.services.databroker.SetSignalRequest =
  `com.sdv.services.databroker`.SetSignalRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.sdv.services.databroker.SetSignalRequestOrBuilder.signalOrNull: sdv.vss.Signals.VehicleSignal?
  get() = if (hasSignal()) getSignal() else null

