// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: services/databroker.proto
// Protobuf Java Version: 4.33.4

package com.sdv.services.databroker;

@com.google.protobuf.Generated
public interface SubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sdv.services.databroker.SubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * VSS signal paths to subscribe to
   * </pre>
   *
   * <code>repeated string signal_paths = 1;</code>
   * @return A list containing the signalPaths.
   */
  java.util.List<java.lang.String>
      getSignalPathsList();
  /**
   * <pre>
   * VSS signal paths to subscribe to
   * </pre>
   *
   * <code>repeated string signal_paths = 1;</code>
   * @return The count of signalPaths.
   */
  int getSignalPathsCount();
  /**
   * <pre>
   * VSS signal paths to subscribe to
   * </pre>
   *
   * <code>repeated string signal_paths = 1;</code>
   * @param index The index of the element to return.
   * @return The signalPaths at the given index.
   */
  java.lang.String getSignalPaths(int index);
  /**
   * <pre>
   * VSS signal paths to subscribe to
   * </pre>
   *
   * <code>repeated string signal_paths = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the signalPaths at the given index.
   */
  com.google.protobuf.ByteString
      getSignalPathsBytes(int index);
}
