// Package store provides the in-memory session store for the mock PARKING_OPERATOR.
package store

import (
	"fmt"
	"sync"
)

// Rate represents the parking rate charged per session.
type Rate struct {
	RateType string  `json:"rate_type"` // "per_hour"
	Amount   float64 `json:"amount"`    // e.g. 2.50
	Currency string  `json:"currency"`  // e.g. "EUR"
}

// Session represents an active or stopped parking session.
type Session struct {
	SessionID string `json:"session_id"`
	VehicleID string `json:"vehicle_id"`
	ZoneID    string `json:"zone_id"`
	Status    string `json:"status"`              // "active" | "stopped"
	StartTime int64  `json:"start_time"`          // unix timestamp
	StopTime  int64  `json:"stop_time,omitempty"` // unix timestamp; 0 when active
	Rate      Rate   `json:"rate"`
}

// StartRequest is the payload for POST /parking/start.
type StartRequest struct {
	VehicleID string `json:"vehicle_id"`
	ZoneID    string `json:"zone_id"`
	Timestamp int64  `json:"timestamp"`
}

// StartResponse is the response body for POST /parking/start.
type StartResponse struct {
	SessionID string `json:"session_id"`
	Status    string `json:"status"`
	Rate      Rate   `json:"rate"`
}

// StopRequest is the payload for POST /parking/stop.
type StopRequest struct {
	SessionID string `json:"session_id"`
	Timestamp int64  `json:"timestamp"`
}

// StopResponse is the response body for POST /parking/stop.
type StopResponse struct {
	SessionID       string  `json:"session_id"`
	Status          string  `json:"status"`
	DurationSeconds int64   `json:"duration_seconds"`
	TotalAmount     float64 `json:"total_amount"`
	Currency        string  `json:"currency"`
}

// defaultRate is the fixed rate applied to all sessions.
var defaultRate = Rate{
	RateType: "per_hour",
	Amount:   2.50,
	Currency: "EUR",
}

// Store is a thread-safe in-memory map of session_id → Session.
type Store struct {
	mu       sync.Mutex
	sessions map[string]*Session
}

// NewStore returns a new empty Store.
func NewStore() *Store {
	return &Store{sessions: make(map[string]*Session)}
}

// Start creates a new session and stores it. The session ID is generated by
// the caller (passed via req). Returns the start response.
func (s *Store) Start(sessionID string, req StartRequest) StartResponse {
	s.mu.Lock()
	defer s.mu.Unlock()

	sess := &Session{
		SessionID: sessionID,
		VehicleID: req.VehicleID,
		ZoneID:    req.ZoneID,
		Status:    "active",
		StartTime: req.Timestamp,
		Rate:      defaultRate,
	}
	s.sessions[sessionID] = sess

	return StartResponse{
		SessionID: sessionID,
		Status:    "active",
		Rate:      defaultRate,
	}
}

// Stop finds a session, marks it stopped, and computes the billing totals.
// Returns ErrNotFound if the session_id does not exist.
func (s *Store) Stop(req StopRequest) (StopResponse, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	sess, ok := s.sessions[req.SessionID]
	if !ok {
		return StopResponse{}, fmt.Errorf("session not found")
	}

	duration := req.Timestamp - sess.StartTime
	totalAmount := sess.Rate.Amount * (float64(duration) / 3600.0)

	sess.Status = "stopped"
	sess.StopTime = req.Timestamp

	return StopResponse{
		SessionID:       req.SessionID,
		Status:          "stopped",
		DurationSeconds: duration,
		TotalAmount:     totalAmount,
		Currency:        sess.Rate.Currency,
	}, nil
}

// GetStatus returns the session with the given ID, or an error if not found.
func (s *Store) GetStatus(sessionID string) (*Session, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	sess, ok := s.sessions[sessionID]
	if !ok {
		return nil, fmt.Errorf("session not found")
	}
	// Return a copy to prevent external mutation of internal state.
	copy := *sess
	return &copy, nil
}
